// Complete team data based on the provided member list
// Organized by role hierarchy and departments

export const completeTeamData = [
  // OWNER/FOUNDER
  {
    _id: 'owner-001',
    _type: 'teamMember',
    name: 'Joshua Kanatt',
    position: 'CEO',
    department: 'leadership',
    bio: 'Visionary Founder & CEO building game-changing technology at GAMERS TAG. Leading one of the world\'s most innovative gaming super platforms.',
    shortBio: 'Building the future of gaming with innovative technology and visionary leadership',
    linkedinUrl: 'https://www.linkedin.com/in/joshuakanatt/',
    expertise: ['Product Management', 'Strategic Leadership', 'Gaming Industry', 'Technology Innovation'],
    isActive: true,
    isFounder: true,
    sortOrder: 1
  },

  // CORE TEAM MEMBERS
  {
    _id: 'core-001',
    _type: 'teamMember',
    name: 'Hemanth Joseph',
    position: 'Core Team Member',
    department: 'leadership',
    bio: 'Core team member driving strategic initiatives and operational excellence at GAMERS TAG.',
    shortBio: 'Strategic leader focused on operational excellence',
    linkedinUrl: 'https://www.hemanthjoseph.com/',
    expertise: ['Strategic Planning', 'Operations Management', 'Team Leadership', 'Business Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 2
  },
  {
    _id: 'core-002',
    _type: 'teamMember',
    name: 'Adesh Kumar Patra',
    position: 'Core Team Member',
    department: 'leadership',
    bio: 'Core team member contributing to strategic decision-making and organizational growth.',
    shortBio: 'Strategic contributor driving organizational growth',
    linkedinUrl: 'https://www.linkedin.com/in/adeshkpatra/',
    expertise: ['Strategic Management', 'Organizational Growth', 'Leadership', 'Project Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 3
  },
  {
    _id: 'core-003',
    _type: 'teamMember',
    name: 'Harsh Singh',
    position: 'Core Tech Member',
    department: 'engineering',
    bio: 'Core technology member leading technical innovation and development excellence.',
    shortBio: 'Technical leader driving innovation',
    linkedinUrl: 'https://www.linkedin.com/in/harsh-singh-639316291/',
    expertise: ['Technical Leadership', 'Software Development', 'Innovation', 'Technology Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 4
  },
  {
    _id: 'core-004',
    _type: 'teamMember',
    name: 'Paul P Dickinson',
    position: 'Core Team Member',
    department: 'operations',
    bio: 'Core team member ensuring operational efficiency and strategic execution.',
    shortBio: 'Operations leader ensuring strategic execution',
    linkedinUrl: 'https://www.linkedin.com/in/paul-dickinson-038511190/',
    expertise: ['Operations Management', 'Strategic Execution', 'Process Optimization', 'Team Coordination'],
    isActive: true,
    isFounder: false,
    sortOrder: 5
  },

  // SENIOR LEADERSHIP
  {
    _id: 'senior-001',
    _type: 'teamMember',
    name: 'Tintu Tomy',
    position: 'Senior Financial Analyst',
    department: 'finance',
    bio: 'Senior financial analyst managing strategic financial planning and analysis.',
    shortBio: 'Expert in financial analysis and strategic planning',
    linkedinUrl: 'https://www.linkedin.com/in/tintu-tomy-93655a24',
    expertise: ['Financial Analysis', 'Strategic Planning'],
    isActive: true,
    isFounder: false,
    sortOrder: 10
  },
  {
    _id: 'senior-002',
    _type: 'teamMember',
    name: 'Nithin George',
    position: 'Senior Product Designer',
    department: 'design',
    bio: 'Senior Product Designer leading design strategy and user experience innovation.',
    shortBio: 'Leading design strategy and user experience innovation',
    linkedinUrl: 'https://www.linkedin.com/in/nithin-george-308a9458/',
    expertise: ['Product Design', 'User Experience', 'Design Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 11
  },
  {
    _id: 'senior-003',
    _type: 'teamMember',
    name: 'Fathima Nihma',
    position: 'Lead HR Manager',
    department: 'hr',
    bio: 'Lead HR Manager driving human resources strategy and talent management.',
    shortBio: 'Leading human resources strategy and talent management',
    linkedinUrl: 'https://www.linkedin.com/in/fathima-nihma',
    expertise: ['HR Strategy', 'Talent Management', 'Team Leadership'],
    isActive: true,
    isFounder: false,
    sortOrder: 12
  },

  // DEVELOPERS
  {
    _id: 'dev-001',
    _type: 'teamMember',
    name: 'Mohd Amber Rizvi',
    position: 'Developer',
    department: 'engineering',
    bio: 'Software developer contributing to technical excellence.',
    shortBio: 'Software developer focused on technical excellence',
    linkedinUrl: 'https://www.linkedin.com/in/mohd-amber-rizvi-93a55a201',
    expertise: ['Software Development', 'Programming', 'Technical Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 100
  },
  {
    _id: 'dev-002',
    _type: 'teamMember',
    name: 'Shivansh Verma',
    position: 'Developer',
    department: 'engineering',
    bio: 'Software developer building innovative solutions.',
    shortBio: 'Software developer building innovative solutions',
    linkedinUrl: 'https://www.linkedin.com/in/meet-shivanshverma',
    expertise: ['Software Development', 'Problem Solving', 'Technical Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 101
  },
  {
    _id: 'dev-003',
    _type: 'teamMember',
    name: 'Jayandra Todawat',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on creating robust technical solutions.',
    shortBio: 'Developer creating robust technical solutions',
    linkedinUrl: 'https://www.linkedin.com/in/jayndra-todawat',
    expertise: ['Software Development', 'Technical Architecture'],
    isActive: true,
    isFounder: false,
    sortOrder: 102
  },
  {
    _id: 'dev-004',
    _type: 'teamMember',
    name: 'Sakshi Dhoni',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to platform innovation.',
    shortBio: 'Developer contributing to platform innovation',
    linkedinUrl: 'https://www.linkedin.com/in/sakshidhoni',
    expertise: ['Software Development', 'Platform Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 103
  },
  {
    _id: 'dev-005',
    _type: 'teamMember',
    name: 'Arjun Gopi K',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer specializing in modern web technologies.',
    shortBio: 'Developer specializing in modern web technologies',
    linkedinUrl: 'https://www.linkedin.com/in/arjun-gopi-k-324178253',
    expertise: ['Web Development', 'Modern Technologies'],
    isActive: true,
    isFounder: false,
    sortOrder: 104
  },
  {
    _id: 'dev-006',
    _type: 'teamMember',
    name: 'Manish Verma',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on scalable solutions.',
    shortBio: 'Developer focused on scalable solutions',
    linkedinUrl: '',
    expertise: ['Software Development', 'Scalable Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 105
  },
  {
    _id: 'dev-007',
    _type: 'teamMember',
    name: 'Ankita Soni',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to technical innovation.',
    shortBio: 'Developer contributing to technical innovation',
    linkedinUrl: 'https://www.linkedin.com/in/aankita-soni',
    expertise: ['Software Development', 'Technical Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 106
  },
  {
    _id: 'dev-008',
    _type: 'teamMember',
    name: 'Aditya Rawat',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer building cutting-edge applications.',
    shortBio: 'Developer building cutting-edge applications',
    linkedinUrl: 'https://www.linkedin.com/in/theadityarawat',
    expertise: ['Application Development', 'Programming'],
    isActive: true,
    isFounder: false,
    sortOrder: 107
  },
  {
    _id: 'dev-009',
    _type: 'teamMember',
    name: 'Utkarsh Kumar Upadhyay',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on technical excellence.',
    shortBio: 'Developer focused on technical excellence',
    linkedinUrl: 'https://www.linkedin.com/in/utkarsh-kumar-upadhyay-18685b24a',
    expertise: ['Software Development', 'Technical Excellence'],
    isActive: true,
    isFounder: false,
    sortOrder: 108
  },
  {
    _id: 'dev-010',
    _type: 'teamMember',
    name: 'Dipankar Upadhyaya',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer creating innovative technical solutions.',
    shortBio: 'Developer creating innovative technical solutions',
    linkedinUrl: 'https://www.linkedin.com/in/dipankar-upadhyaya-26618b238',
    expertise: ['Software Development', 'Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 109
  },
  {
    _id: 'dev-011',
    _type: 'teamMember',
    name: 'Sakshi Soni',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer specializing in modern development practices.',
    shortBio: 'Developer specializing in modern development practices',
    linkedinUrl: 'https://www.linkedin.com/in/sakshidhoni',
    expertise: ['Modern Development', 'Best Practices'],
    isActive: true,
    isFounder: false,
    sortOrder: 110
  },
  {
    _id: 'dev-012',
    _type: 'teamMember',
    name: 'Shreyansh Khandelwal',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer building robust software solutions.',
    shortBio: 'Developer building robust software solutions',
    linkedinUrl: 'https://www.linkedin.com/in/shreyansh-khandelwal-383718165',
    expertise: ['Software Development', 'Robust Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 111
  },
  {
    _id: 'dev-013',
    _type: 'teamMember',
    name: 'Vaidant Sharma',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on innovative programming solutions.',
    shortBio: 'Developer focused on innovative programming solutions',
    linkedinUrl: 'https://www.linkedin.com/in/vaidant-sharma-7435592a4',
    expertise: ['Programming', 'Innovative Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 112
  },
  {
    _id: 'dev-014',
    _type: 'teamMember',
    name: 'Prakhar Singh',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to platform development.',
    shortBio: 'Developer contributing to platform development',
    linkedinUrl: 'https://www.linkedin.com/in/meet-prakhar-singh',
    expertise: ['Platform Development', 'Software Engineering'],
    isActive: true,
    isFounder: false,
    sortOrder: 113
  },
  {
    _id: 'dev-015',
    _type: 'teamMember',
    name: 'Shivam Chouhan',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer building scalable applications.',
    shortBio: 'Developer building scalable applications',
    linkedinUrl: 'https://www.linkedin.com/in/shivam-chouhan',
    expertise: ['Application Development', 'Scalability'],
    isActive: true,
    isFounder: false,
    sortOrder: 114
  },
  {
    _id: 'dev-016',
    _type: 'teamMember',
    name: 'Swapnil Adsul',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on technical innovation.',
    shortBio: 'Developer focused on technical innovation',
    linkedinUrl: 'https://www.linkedin.com/in/swapnil-adsul-139515230',
    expertise: ['Technical Innovation', 'Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 115
  },
  {
    _id: 'dev-017',
    _type: 'teamMember',
    name: 'Shubh Agrawal',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer creating efficient software solutions.',
    shortBio: 'Developer creating efficient software solutions',
    linkedinUrl: 'https://www.linkedin.com/in/shubhagarwal0704',
    expertise: ['Software Development', 'Efficiency'],
    isActive: true,
    isFounder: false,
    sortOrder: 116
  },
  {
    _id: 'dev-018',
    _type: 'teamMember',
    name: 'Aman Nurmhamad Mujawar',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to technical excellence.',
    shortBio: 'Developer contributing to technical excellence',
    linkedinUrl: '',
    expertise: ['Software Development', 'Technical Excellence'],
    isActive: true,
    isFounder: false,
    sortOrder: 117
  },
  {
    _id: 'dev-019',
    _type: 'teamMember',
    name: 'Lavanya Talodhikar',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer building innovative applications.',
    shortBio: 'Developer building innovative applications',
    linkedinUrl: 'https://www.linkedin.com/in/lawanya-talodhikar-2688942a4',
    expertise: ['Application Development', 'Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 118
  },
  {
    _id: 'dev-020',
    _type: 'teamMember',
    name: 'Ranjima AR',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer specializing in modern web technologies.',
    shortBio: 'Developer specializing in modern web technologies',
    linkedinUrl: 'https://www.linkedin.com/in/ranjima-ar',
    expertise: ['Web Development', 'Modern Technologies'],
    isActive: true,
    isFounder: false,
    sortOrder: 119
  },
  {
    _id: 'dev-021',
    _type: 'teamMember',
    name: 'Aman Kumar',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on robust software solutions.',
    shortBio: 'Developer focused on robust software solutions',
    linkedinUrl: 'https://www.linkedin.com/in/ACoAAEeg9S4Baj86sVm9R5LVUqfHjeMNEq0rcDA',
    expertise: ['Software Development', 'Robust Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 120
  },

  // SOCIAL MEDIA MANAGERS
  {
    _id: 'smm-001',
    _type: 'teamMember',
    name: 'Ditto Johnson',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager driving digital engagement and brand presence.',
    shortBio: 'Driving digital engagement and brand presence',
    linkedinUrl: 'https://www.linkedin.com/in/ditto-johnson-941267249',
    expertise: ['Social Media Marketing', 'Digital Engagement', 'Brand Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 200
  },
  {
    _id: 'smm-002',
    _type: 'teamMember',
    name: 'Aiswarya Madhu',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager creating engaging digital content.',
    shortBio: 'Creating engaging digital content',
    linkedinUrl: 'https://www.linkedin.com/in/vallathaiswarya',
    expertise: ['Content Creation', 'Digital Marketing', 'Social Media Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 201
  },
  {
    _id: 'smm-003',
    _type: 'teamMember',
    name: 'Gautam Krishna K',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager specializing in brand storytelling.',
    shortBio: 'Specializing in brand storytelling',
    linkedinUrl: 'https://www.linkedin.com/in/ACoAAEQ2Et4B8sLMLpi2zVd6IxWnwojTH8EyK-s',
    expertise: ['Brand Storytelling', 'Social Media', 'Digital Content'],
    isActive: true,
    isFounder: false,
    sortOrder: 202
  },
  {
    _id: 'smm-004',
    _type: 'teamMember',
    name: 'Abhinaya R',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager focused on community engagement.',
    shortBio: 'Focused on community engagement',
    linkedinUrl: 'https://www.linkedin.com/in/abhinaya-ravic',
    expertise: ['Community Engagement', 'Social Media', 'Digital Marketing'],
    isActive: true,
    isFounder: false,
    sortOrder: 203
  },
  {
    _id: 'smm-005',
    _type: 'teamMember',
    name: 'Naman Sharma',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager driving online presence.',
    shortBio: 'Driving online presence and engagement',
    linkedinUrl: 'https://www.linkedin.com/in/naman-sharma-682189244',
    expertise: ['Online Presence', 'Social Media Strategy', 'Digital Engagement'],
    isActive: true,
    isFounder: false,
    sortOrder: 204
  },

  // HR MANAGERS
  {
    _id: 'hr-001',
    _type: 'teamMember',
    name: 'Himani Sharma',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager focused on talent acquisition and development.',
    shortBio: 'Focused on talent acquisition and development',
    linkedinUrl: 'https://www.linkedin.com/in/himanisharma062',
    expertise: ['Talent Acquisition', 'HR Development', 'Team Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 300
  },
  {
    _id: 'hr-002',
    _type: 'teamMember',
    name: 'Suhitha Suresh',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager specializing in employee relations.',
    shortBio: 'Specializing in employee relations',
    linkedinUrl: 'https://www.linkedin.com/in/suhitha1722',
    expertise: ['Employee Relations', 'HR Management', 'Organizational Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 301
  },
  {
    _id: 'hr-003',
    _type: 'teamMember',
    name: 'Rishitha Jain',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager driving human resources strategy.',
    shortBio: 'Driving human resources strategy',
    linkedinUrl: 'https://www.linkedin.com/in/rishita-jain-24890b30a',
    expertise: ['HR Strategy', 'People Management', 'Organizational Growth'],
    isActive: true,
    isFounder: false,
    sortOrder: 302
  },
  {
    _id: 'hr-004',
    _type: 'teamMember',
    name: 'Sukhmani Kaur',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager focused on team development.',
    shortBio: 'Focused on team development',
    linkedinUrl: 'https://www.linkedin.com/in/itssukhmanikaur',
    expertise: ['Team Development', 'HR Operations', 'Talent Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 303
  },

  // BRAND MANAGERS
  {
    _id: 'brand-001',
    _type: 'teamMember',
    name: 'Shamil Mohamed',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager driving brand strategy and market presence.',
    shortBio: 'Driving brand strategy and market presence',
    linkedinUrl: 'https://www.linkedin.com/in/muhammed-shamil-thottungal',
    expertise: ['Brand Strategy', 'Market Presence', 'Brand Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 400
  },
  {
    _id: 'brand-002',
    _type: 'teamMember',
    name: 'Philip George',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager focused on brand innovation.',
    shortBio: 'Focused on brand innovation',
    linkedinUrl: 'https://www.linkedin.com/in/philip-george-408786216',
    expertise: ['Brand Innovation', 'Marketing Strategy', 'Brand Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 401
  },
  {
    _id: 'brand-003',
    _type: 'teamMember',
    name: 'Amruth',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager specializing in brand development.',
    shortBio: 'Specializing in brand development',
    linkedinUrl: 'https://www.linkedin.com/in/amruth-n',
    expertise: ['Brand Development', 'Strategic Marketing', 'Brand Positioning'],
    isActive: true,
    isFounder: false,
    sortOrder: 402
  },

  // FINANCIAL ANALYSTS
  {
    _id: 'finance-001',
    _type: 'teamMember',
    name: 'Dibin Jose Vadakkan',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst managing financial planning and analysis.',
    shortBio: 'Managing financial planning and analysis',
    linkedinUrl: 'https://www.linkedin.com/in/dibin-jose-vadakkan-69109179',
    expertise: ['Financial Analysis', 'Financial Planning', 'Data Analysis'],
    isActive: true,
    isFounder: false,
    sortOrder: 500
  },
  {
    _id: 'finance-002',
    _type: 'teamMember',
    name: 'Mariya Joshy',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst focused on strategic financial insights.',
    shortBio: 'Focused on strategic financial insights',
    linkedinUrl: 'https://www.linkedin.com/in/mariya-joshy-97bba4222',
    expertise: ['Financial Insights', 'Strategic Analysis', 'Financial Reporting'],
    isActive: true,
    isFounder: false,
    sortOrder: 501
  },
  {
    _id: 'finance-003',
    _type: 'teamMember',
    name: 'Abhishek S Nair',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst specializing in financial modeling.',
    shortBio: 'Specializing in financial modeling',
    linkedinUrl: 'https://www.linkedin.com/in/abhishek-s-nair50',
    expertise: ['Financial Modeling', 'Data Analysis', 'Financial Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 502
  },
  {
    _id: 'finance-004',
    _type: 'teamMember',
    name: 'Abel Antony',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst driving financial excellence.',
    shortBio: 'Driving financial excellence',
    linkedinUrl: 'https://www.linkedin.com/in/abel-antony-benny',
    expertise: ['Financial Excellence', 'Analysis', 'Strategic Planning'],
    isActive: true,
    isFounder: false,
    sortOrder: 503
  },

  // DESIGN TEAM MEMBERS
  {
    _id: 'design-001',
    _type: 'teamMember',
    name: 'Haniya Abdul Rahman',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating engaging visual experiences.',
    shortBio: 'Creating engaging visual experiences',
    linkedinUrl: 'https://www.linkedin.com/in/haniya-ar',
    expertise: ['Visual Design', 'User Interface', 'Creative Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 600
  },
  {
    _id: 'design-002',
    _type: 'teamMember',
    name: 'Nithin Dhawane',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member focused on user experience.',
    shortBio: 'Focused on user experience design',
    linkedinUrl: 'https://www.linkedin.com/in/nitin-dhawane-39b07515a',
    expertise: ['User Experience', 'Design Thinking', 'Interface Design'],
    isActive: true,
    isFounder: false,
    sortOrder: 601
  },
  {
    _id: 'design-003',
    _type: 'teamMember',
    name: 'Kevin George',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member specializing in creative solutions.',
    shortBio: 'Specializing in creative design solutions',
    linkedinUrl: 'https://www.linkedin.com/in/kevin-george-58b5701a1',
    expertise: ['Creative Solutions', 'Visual Design', 'Design Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 602
  },
  {
    _id: 'design-004',
    _type: 'teamMember',
    name: 'Alen Joshy',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating innovative designs.',
    shortBio: 'Creating innovative design solutions',
    linkedinUrl: 'https://www.linkedin.com/in/alen-joshy-4025a41bb',
    expertise: ['Innovative Design', 'Creative Thinking', 'Visual Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 603
  },
  {
    _id: 'design-005',
    _type: 'teamMember',
    name: 'Ahammed Habeebi',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member focused on visual excellence.',
    shortBio: 'Focused on visual excellence',
    linkedinUrl: 'https://www.linkedin.com/in/ahammed-habeebi-b4997021a',
    expertise: ['Visual Excellence', 'Design Quality', 'Creative Design'],
    isActive: true,
    isFounder: false,
    sortOrder: 604
  },
  {
    _id: 'design-006',
    _type: 'teamMember',
    name: 'Suhani Goyal',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating impactful designs.',
    shortBio: 'Creating impactful design solutions',
    linkedinUrl: 'https://www.linkedin.com/in/suhanieie',
    expertise: ['Impact Design', 'Visual Communication', 'Creative Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 605
  },
  {
    _id: 'design-007',
    _type: 'teamMember',
    name: 'Minnathullaa S',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member specializing in user-centered design.',
    shortBio: 'Specializing in user-centered design',
    linkedinUrl: 'https://www.linkedin.com/in/minnathullaa-s-664694242',
    expertise: ['User-Centered Design', 'Design Research', 'Visual Design'],
    isActive: true,
    isFounder: false,
    sortOrder: 606
  },

  // APP TESTERS
  {
    _id: 'qa-001',
    _type: 'teamMember',
    name: 'Jilha Jose',
    position: 'App Tester',
    department: 'qa',
    bio: 'App Tester ensuring quality and performance excellence.',
    shortBio: 'Ensuring quality and performance excellence',
    linkedinUrl: 'https://www.linkedin.com/in/jilha-jos/',
    expertise: ['Quality Assurance', 'Testing', 'Performance Analysis'],
    isActive: true,
    isFounder: false,
    sortOrder: 700
  },
  {
    _id: 'qa-002',
    _type: 'teamMember',
    name: 'Ardra Shashidharan',
    position: 'App Tester',
    department: 'qa',
    bio: 'App Tester focused on comprehensive testing solutions.',
    shortBio: 'Focused on comprehensive testing solutions',
    linkedinUrl: 'https://www.linkedin.com/in/ardra-sasidharan-05a861211',
    expertise: ['Comprehensive Testing', 'Quality Control', 'Bug Detection'],
    isActive: true,
    isFounder: false,
    sortOrder: 701
  },

  // ESPORTS MANAGERS
  {
    _id: 'esports-001',
    _type: 'teamMember',
    name: 'Jeethu Singh',
    position: 'Esports Manager',
    department: 'esports',
    bio: 'Esports Manager driving competitive gaming initiatives.',
    shortBio: 'Driving competitive gaming initiatives',
    linkedinUrl: 'https://www.linkedin.com/in/jeetu-singh-574665292',
    expertise: ['Esports Management', 'Competitive Gaming', 'Event Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 800
  },
  {
    _id: 'esports-002',
    _type: 'teamMember',
    name: 'Indrajith Ajith',
    position: 'Esports Manager',
    department: 'esports',
    bio: 'Esports Manager specializing in tournament organization.',
    shortBio: 'Specializing in tournament organization',
    linkedinUrl: '',
    expertise: ['Tournament Management', 'Esports Strategy', 'Gaming Events'],
    isActive: true,
    isFounder: false,
    sortOrder: 801
  },

  // VIDEO EDITORS
  {
    _id: 'video-001',
    _type: 'teamMember',
    name: 'Shubham Chintal',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor creating engaging multimedia content.',
    shortBio: 'Creating engaging multimedia content',
    linkedinUrl: 'https://www.linkedin.com/in/shubham-chintal-254683292',
    expertise: ['Video Editing', 'Multimedia Content', 'Creative Production'],
    isActive: true,
    isFounder: false,
    sortOrder: 900
  },
  {
    _id: 'video-002',
    _type: 'teamMember',
    name: 'Mukul Singh Morawat',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor specializing in content production.',
    shortBio: 'Specializing in content production',
    linkedinUrl: 'https://www.linkedin.com/in/mukul-singh-morawat-1386bb255/',
    expertise: ['Content Production', 'Video Editing', 'Visual Storytelling'],
    isActive: true,
    isFounder: false,
    sortOrder: 901
  },
  {
    _id: 'video-003',
    _type: 'teamMember',
    name: 'Saloni Dhanotiya',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor focused on creative video solutions.',
    shortBio: 'Focused on creative video solutions',
    linkedinUrl: 'https://www.linkedin.com/in/saloni-dhanotiya-00615125a',
    expertise: ['Creative Video', 'Post Production', 'Visual Effects'],
    isActive: true,
    isFounder: false,
    sortOrder: 902
  },

  // ADDITIONAL TEAM MEMBERS FROM COMPLETE LIST
  {
    _id: 'dev-022',
    _type: 'teamMember',
    name: 'Dumpala Pardha Saradhi',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on robust software solutions.',
    shortBio: 'Developer focused on robust software solutions',
    linkedinUrl: 'https://www.linkedin.com/in/pardha-saradhi-818a93254',
    expertise: ['Software Development', 'Programming'],
    isActive: true,
    isFounder: false,
    sortOrder: 121
  },
  {
    _id: 'dev-023',
    _type: 'teamMember',
    name: 'Shivansh Shukla',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer building innovative programming solutions.',
    shortBio: 'Developer building innovative programming solutions',
    linkedinUrl: 'https://www.linkedin.com/in/shukla-programmer',
    expertise: ['Programming', 'Software Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 122
  },
  {
    _id: 'video-004',
    _type: 'teamMember',
    name: 'Alen Joe Abey',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor creating engaging multimedia content.',
    shortBio: 'Creating engaging multimedia content',
    linkedinUrl: 'https://www.linkedin.com/in/alen-joe-abey-50603a311',
    expertise: ['Video Editing', 'Multimedia Content'],
    isActive: true,
    isFounder: false,
    sortOrder: 903
  },
  {
    _id: 'video-005',
    _type: 'teamMember',
    name: 'Ayush Anand',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor specializing in creative content production.',
    shortBio: 'Specializing in creative content production',
    linkedinUrl: 'https://www.linkedin.com/in/ACoAAD1vndIBXzxjlwOq_5zStBEHtDcexrwtHVw',
    expertise: ['Video Editing', 'Creative Content'],
    isActive: true,
    isFounder: false,
    sortOrder: 904
  },
  {
    _id: 'hr-005',
    _type: 'teamMember',
    name: 'Iti Jain',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager focused on talent development.',
    shortBio: 'Focused on talent development',
    linkedinUrl: '',
    expertise: ['HR Management', 'Talent Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 304
  },
  {
    _id: 'hr-006',
    _type: 'teamMember',
    name: 'Kartheek Chilukoti',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager specializing in organizational development.',
    shortBio: 'Specializing in organizational development',
    linkedinUrl: 'https://www.linkedin.com/in/kartheek-chilukoti-038185228',
    expertise: ['Organizational Development', 'HR Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 305
  },
  {
    _id: 'hr-007',
    _type: 'teamMember',
    name: 'Poojitha Pasham',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager driving employee engagement.',
    shortBio: 'Driving employee engagement',
    linkedinUrl: 'https://www.linkedin.com/in/poojitha-pasham-2355652a1',
    expertise: ['Employee Engagement', 'HR Operations'],
    isActive: true,
    isFounder: false,
    sortOrder: 306
  },
  {
    _id: 'hr-008',
    _type: 'teamMember',
    name: 'Butool Zehra Jafri',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager focused on talent acquisition.',
    shortBio: 'Focused on talent acquisition',
    linkedinUrl: 'https://www.linkedin.com/in/butoolzehra30',
    expertise: ['Talent Acquisition', 'HR Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 307
  },
  {
    _id: 'hr-009',
    _type: 'teamMember',
    name: 'Mannat Malhotra',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager specializing in people development.',
    shortBio: 'Specializing in people development',
    linkedinUrl: 'https://www.linkedin.com/in/mannat-malhotra-82900a216',
    expertise: ['People Development', 'HR Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 308
  },
  {
    _id: 'content-001',
    _type: 'teamMember',
    name: 'Saanvi Rana',
    position: 'Content Writer',
    department: 'content',
    bio: 'Content Writer creating engaging written content.',
    shortBio: 'Creating engaging written content',
    linkedinUrl: 'https://www.linkedin.com/in/saanvi-rana-082843256/',
    expertise: ['Content Writing', 'Creative Writing'],
    isActive: true,
    isFounder: false,
    sortOrder: 1000
  },
  {
    _id: 'content-002',
    _type: 'teamMember',
    name: 'Alina Joseph',
    position: 'Content Writer',
    department: 'content',
    bio: 'Content Writer specializing in digital content.',
    shortBio: 'Specializing in digital content',
    linkedinUrl: 'https://www.linkedin.com/in/alinajoseph08',
    expertise: ['Digital Content', 'Content Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 1001
  },
  {
    _id: 'dev-024',
    _type: 'teamMember',
    name: 'Himanshu Gupta',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer building scalable applications.',
    shortBio: 'Developer building scalable applications',
    linkedinUrl: 'https://www.linkedin.com/in/himanshu-gupta-33491b1ba',
    expertise: ['Application Development', 'Scalability'],
    isActive: true,
    isFounder: false,
    sortOrder: 123
  },
  {
    _id: 'smm-006',
    _type: 'teamMember',
    name: 'Anushka Sharma',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager driving digital engagement.',
    shortBio: 'Driving digital engagement',
    linkedinUrl: 'https://www.linkedin.com/in/anushkasharma2211/',
    expertise: ['Digital Engagement', 'Social Media Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 205
  },
  {
    _id: 'finance-005',
    _type: 'teamMember',
    name: 'Jen Joy',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst focused on data-driven insights.',
    shortBio: 'Focused on data-driven insights',
    linkedinUrl: 'https://www.linkedin.com/in/jentjoy',
    expertise: ['Financial Analysis', 'Data Insights'],
    isActive: true,
    isFounder: false,
    sortOrder: 504
  },
  {
    _id: 'content-003',
    _type: 'teamMember',
    name: 'Neha Chandrasekaran',
    position: 'Content Writer',
    department: 'content',
    bio: 'Content Writer creating compelling narratives.',
    shortBio: 'Creating compelling narratives',
    linkedinUrl: 'https://www.linkedin.com/in/neha-chandrasekaran',
    expertise: ['Content Writing', 'Storytelling'],
    isActive: true,
    isFounder: false,
    sortOrder: 1002
  },
  {
    _id: 'video-006',
    _type: 'teamMember',
    name: 'Arun Kumar',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor specializing in post-production.',
    shortBio: 'Specializing in post-production',
    linkedinUrl: 'https://www.linkedin.com/in/arunkumar12533',
    expertise: ['Video Editing', 'Post Production'],
    isActive: true,
    isFounder: false,
    sortOrder: 905
  },
  {
    _id: 'smm-007',
    _type: 'teamMember',
    name: 'Muhammed Shahin',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager creating brand awareness.',
    shortBio: 'Creating brand awareness',
    linkedinUrl: 'https://www.linkedin.com/in/muhammed-shahin-u-52a444210',
    expertise: ['Brand Awareness', 'Social Media Marketing'],
    isActive: true,
    isFounder: false,
    sortOrder: 206
  },
  {
    _id: 'video-007',
    _type: 'teamMember',
    name: 'Simontika Das',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor focused on creative storytelling.',
    shortBio: 'Focused on creative storytelling',
    linkedinUrl: 'https://www.linkedin.com/in/simontika-das-9607402a5',
    expertise: ['Video Editing', 'Creative Storytelling'],
    isActive: true,
    isFounder: false,
    sortOrder: 906
  },
  {
    _id: 'design-008',
    _type: 'teamMember',
    name: 'Snehal Mathur',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating visual solutions.',
    shortBio: 'Creating visual solutions',
    linkedinUrl: 'https://www.linkedin.com/in/snehalmathur2005/',
    expertise: ['Visual Design', 'Creative Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 607
  },
  {
    _id: 'finance-006',
    _type: 'teamMember',
    name: 'Nasrin K',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst driving strategic insights.',
    shortBio: 'Driving strategic insights',
    linkedinUrl: 'https://www.linkedin.com/in/nasrin-k',
    expertise: ['Strategic Analysis', 'Financial Planning'],
    isActive: true,
    isFounder: false,
    sortOrder: 505
  },
  {
    _id: 'finance-007',
    _type: 'teamMember',
    name: 'Jerin Mathew',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst focused on financial modeling.',
    shortBio: 'Focused on financial modeling',
    linkedinUrl: 'https://www.linkedin.com/in/jerin-mathew-60214a1b9',
    expertise: ['Financial Modeling', 'Data Analysis'],
    isActive: true,
    isFounder: false,
    sortOrder: 506
  },
  {
    _id: 'video-008',
    _type: 'teamMember',
    name: 'Baishali Dey Sarkar',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor creating engaging visual content.',
    shortBio: 'Creating engaging visual content',
    linkedinUrl: 'https://www.linkedin.com/in/baishali-dey-sarkar-663b6232a',
    expertise: ['Video Editing', 'Visual Content'],
    isActive: true,
    isFounder: false,
    sortOrder: 907
  },
  {
    _id: 'video-009',
    _type: 'teamMember',
    name: 'Sonu Dabi',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor specializing in multimedia production.',
    shortBio: 'Specializing in multimedia production',
    linkedinUrl: 'https://www.linkedin.com/in/sonu-dabi',
    expertise: ['Video Editing', 'Multimedia Production'],
    isActive: true,
    isFounder: false,
    sortOrder: 908
  },
  {
    _id: 'brand-004',
    _type: 'teamMember',
    name: 'Zeeshan Siddiqui',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager driving brand strategy.',
    shortBio: 'Driving brand strategy',
    linkedinUrl: 'https://www.linkedin.com/in/zeeshan-siddiqui-a93197249',
    expertise: ['Brand Strategy', 'Marketing'],
    isActive: true,
    isFounder: false,
    sortOrder: 403
  },
  {
    _id: 'design-009',
    _type: 'teamMember',
    name: 'Vamsi Karthik',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member focused on user interface design.',
    shortBio: 'Focused on user interface design',
    linkedinUrl: 'https://www.linkedin.com/in/vamsi-karthik555',
    expertise: ['UI Design', 'Visual Design'],
    isActive: true,
    isFounder: false,
    sortOrder: 608
  },
  {
    _id: 'brand-005',
    _type: 'teamMember',
    name: 'Shubham Kumar',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager specializing in brand development.',
    shortBio: 'Specializing in brand development',
    linkedinUrl: 'https://www.linkedin.com/in/shubham-kumar-6a4804211',
    expertise: ['Brand Development', 'Marketing Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 404
  },
  {
    _id: 'design-010',
    _type: 'teamMember',
    name: 'Anusha Popat',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating innovative designs.',
    shortBio: 'Creating innovative designs',
    linkedinUrl: 'https://www.linkedin.com/in/anusha-popat-b199802a5',
    expertise: ['Innovative Design', 'Creative Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 609
  },
  {
    _id: 'design-011',
    _type: 'teamMember',
    name: 'Taniya Jahagirdar',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member focused on visual excellence.',
    shortBio: 'Focused on visual excellence',
    linkedinUrl: 'https://www.linkedin.com/in/ACoAADicdL8Bpq4GiOZySaxIwzeHWMKXIQeVJvc',
    expertise: ['Visual Excellence', 'Design Quality'],
    isActive: true,
    isFounder: false,
    sortOrder: 610
  },
  {
    _id: 'dev-025',
    _type: 'teamMember',
    name: 'Ojash Gupta',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer building modern applications.',
    shortBio: 'Developer building modern applications',
    linkedinUrl: 'https://www.linkedin.com/in/ojash-gupta-7a755b1bb',
    expertise: ['Application Development', 'Modern Technologies'],
    isActive: true,
    isFounder: false,
    sortOrder: 124
  },
  {
    _id: 'design-012',
    _type: 'teamMember',
    name: 'Subhiksha Prabakaran',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member specializing in user experience.',
    shortBio: 'Specializing in user experience',
    linkedinUrl: 'https://www.linkedin.com/in/subhiksha-prabakaran-101475135',
    expertise: ['User Experience', 'Design Research'],
    isActive: true,
    isFounder: false,
    sortOrder: 611
  },
  {
    _id: 'dev-026',
    _type: 'teamMember',
    name: 'Prakhar Jain',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on technical innovation.',
    shortBio: 'Developer focused on technical innovation',
    linkedinUrl: 'http://www.linkedin.com/in/peter1prakhar',
    expertise: ['Technical Innovation', 'Software Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 125
  },
  {
    _id: 'brand-006',
    _type: 'teamMember',
    name: 'Sagar Sharma',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager driving market presence.',
    shortBio: 'Driving market presence',
    linkedinUrl: 'https://www.linkedin.com/in/ACoAACl_Cg4BMmMq_3SCQncdNOrZrfsV045R91A',
    expertise: ['Market Presence', 'Brand Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 405
  },
  {
    _id: 'brand-007',
    _type: 'teamMember',
    name: 'Monish Goutham',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager focused on brand innovation.',
    shortBio: 'Focused on brand innovation',
    linkedinUrl: 'https://www.linkedin.com/in/ACoAAC9UoCoBDdcQJuuLc_6WGn_4oPxg0z8sDZ8',
    expertise: ['Brand Innovation', 'Strategic Marketing'],
    isActive: true,
    isFounder: false,
    sortOrder: 406
  },
  {
    _id: 'dev-027',
    _type: 'teamMember',
    name: 'Dhruv Goel',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer creating efficient solutions.',
    shortBio: 'Developer creating efficient solutions',
    linkedinUrl: 'https://www.linkedin.com/in/dhruv1100',
    expertise: ['Efficient Solutions', 'Software Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 126
  },
  {
    _id: 'dev-028',
    _type: 'teamMember',
    name: 'Asjad Raza',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer building innovative applications.',
    shortBio: 'Developer building innovative applications',
    linkedinUrl: 'https://www.linkedin.com/in/vedasjad',
    expertise: ['Application Development', 'Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 127
  },
  {
    _id: 'design-013',
    _type: 'teamMember',
    name: 'Umit Vadgama',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating impactful designs.',
    shortBio: 'Creating impactful designs',
    linkedinUrl: 'https://www.linkedin.com/in/umitvadgama/',
    expertise: ['Impact Design', 'Visual Communication'],
    isActive: true,
    isFounder: false,
    sortOrder: 612
  },
  {
    _id: 'dev-029',
    _type: 'teamMember',
    name: 'Sundharam',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on software solutions.',
    shortBio: 'Developer focused on software solutions',
    linkedinUrl: '',
    expertise: ['Software Development', 'Problem Solving'],
    isActive: true,
    isFounder: false,
    sortOrder: 128
  },
  {
    _id: 'dev-030',
    _type: 'teamMember',
    name: 'Divyansh Gandotra',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer building scalable systems.',
    shortBio: 'Developer building scalable systems',
    linkedinUrl: 'https://www.linkedin.com/in/divyansh-gandotra-625aa1276',
    expertise: ['Scalable Systems', 'Software Architecture'],
    isActive: true,
    isFounder: false,
    sortOrder: 129
  },
  {
    _id: 'dev-031',
    _type: 'teamMember',
    name: 'Ganesh S',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer creating robust applications.',
    shortBio: 'Developer creating robust applications',
    linkedinUrl: 'https://www.linkedin.com/in/ganesh-s-34874924b',
    expertise: ['Application Development', 'Software Engineering'],
    isActive: true,
    isFounder: false,
    sortOrder: 130
  },
  {
    _id: 'dev-032',
    _type: 'teamMember',
    name: 'Himani Srivastava',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer specializing in modern technologies.',
    shortBio: 'Developer specializing in modern technologies',
    linkedinUrl: 'https://www.linkedin.com/in/himani-srivastava',
    expertise: ['Modern Technologies', 'Software Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 131
  },
  {
    _id: 'dev-033',
    _type: 'teamMember',
    name: 'Utpal Tiwari',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer building innovative solutions.',
    shortBio: 'Developer building innovative solutions',
    linkedinUrl: 'https://www.linkedin.com/in/utpal-tiwari-b6ab10203',
    expertise: ['Innovative Solutions', 'Programming'],
    isActive: true,
    isFounder: false,
    sortOrder: 132
  },
  {
    _id: 'dev-034',
    _type: 'teamMember',
    name: 'Sundaram Pandey',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on technical excellence.',
    shortBio: 'Developer focused on technical excellence',
    linkedinUrl: 'https://www.linkedin.com/in/sundaram-pandey-155043237',
    expertise: ['Technical Excellence', 'Software Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 133
  }
];