// Demo data that would come from Sanity CMS - Authentic team members from GAMERS TAG
// This simulates the structure of data returned from Sanity queries

// Import the comprehensive team data
import { comprehensiveTeamData } from './updated-team-data';

// Updated team data with comprehensive member list
export const allAuthenticTeamMembers = comprehensiveTeamData;

// Keep the original structure for backwards compatibility
export const originalTeamMembers = [
  // Top 5 Core Leadership Team
  {
    _id: 'team-001',
    _type: 'teamMember',
    _createdAt: '2023-01-01T00:00:00Z',
    _updatedAt: '2024-01-01T00:00:00Z',
    _rev: 'rev-001',
    name: 'Joshua J Kanatt',
    position: 'Founder & Chief Executive Officer',
    department: 'leadership',
    bio: 'I\'m a founder on a mission to increase global gaming valuation to 5x in next 5 year also set new global standards for startups. I\'ve built one of the world\'s most innovative gaming super platforms, integrating deep design principles, advanced gamification, AI, SaaS, and community-first strategies. A rare combination of Founder & CEO who is a Product Leader, Technologist, Marketer, Analyst, AI Researcher, Financial Strategist, HR Architect, and Startups expert. As the Founder of Gamers Tag, I\'ve crafted over 50+ products launched, 350+ professionals led, and 200+ businesses consulted, I\'ve engineered one of the world\'s most innovative gaming super platforms at Gamers Tag, architecting 24+ Game Tech products, 20,000+ wireframes, and industry-first solutions like the Neumorphic V2 3D UI (96% user acceptance).',
    shortBio: 'Visionary Builder of Game-Changing Tech',
    personalDetails: {
      aboutMe: 'I\'m a founder on a mission to increase global gaming valuation to 5x in next 5 year also set new global standards for startups. I don\'t just dream; I execute fast, turning vision into real-world impact. Beyond business, I\'m a gamer and sportsman at heart. I actively play badminton, football, basketball, volleyball, and cricket. I\'m deeply inspired by legends like Lionel Messi, Derrick Rose, Kobe Bryant, and Lewis Hamilton and not just for their greatness, but for their resilience, precision, and obsession with mastery.',
      whatIDo: 'I don\'t just lead, I build from the ground up, every single day. I\'m a founder who\'s hands-on across every department, from Product to Technology, from Marketing to Sales, from Design to Analytics, from Research to Finance, from HR to Investor Relations. My leadership style is simple: be the chill founder who builds entrepreneurs. I empower my team to take ownership, to challenge conventions, and to bring the absolute best version of themselves to the table.',
      mission: 'My ultimate goal? To become one of the world\'s most impactful founder. I believe in building people, not just products. By fostering their strengths and championing their ideas, we don\'t just build a company, we build dreams, legacies, and the future of gaming itself.'
    },
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-joshua', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/joshuakanatt/',
    website: 'https://www.joshuakanatt.com/',
    expertise: [
      'Product Management & Strategy',
      'Full-Stack Product Ownership', 
      'SaaS, AI, Fintech, Gaming, EdTech',
      'UI/UX (Neumorphic, 3D Design, Figma)',
      'Data Science & ML Integration',
      'Deep Market & User Research',
      'Go-To-Market Execution',
      'Business Development',
      'Performance Marketing & SEO',
      'Fundraising, Valuation, and Pitching',
      'Financial Modeling & Investor Relations',
      'HR Systems & Talent Management',
      'Strategic Planning & Analytics',
      'Community Building & Affiliate Marketing',
      'Creative Direction & Brand Identity'
    ],
    education: [
      'Deakin Business School, Australia – GMBA, Leadership & Management (Dec 2023 – Apr 2025)',
      'Stanford Graduate School of Business – Stanford Seed Spark Program (Feb 2023 – Jul 2023)',
      'IMT Ghaziabad – PGDM, Data Science',
      'Liverpool John Moores University, UK – M.S. in Data Science',
      'IIIT Bangalore – PG Program in Data Science',
      'Hindusthan College of Engineering & Tech – B.Tech in Computer Science'
    ],
    incubators: [
      'Stanford Seed Spark Program (Stanford GSB)',
      'Razorpay Rize',
      'NASSCOM 10000 Startups',
      'Cisco LaunchPad',
      'Wadhwani Foundation',
      'Atal Innovation Mission (AIM)',
      'PDEU Innovation & Incubation Centre',
      'Kerala Startup Mission (KSUM)'
    ],
    achievements: [
      '50+ Products Launched',
      '350+ Professionals Led',
      '200+ Businesses Consulted',
      '24+ Game Tech Products Architected',
      '20,000+ Wireframes Created',
      'Neumorphic V2 3D UI (96% user acceptance)',
      'Stanford Seed Spark Program Graduate',
      'Multiple Incubator Programs'
    ],
    quote: 'The global gaming industry is not just growing; it\'s exploding, projected to surge from $310.97 billion in 2024 to $562.87 billion by 2029, at a compound annual growth rate (CAGR) of 13.0%. With over 3.3 billion players worldwide and an expected rise to 3.5+ billion in 2025, Gamers Tag is strategically positioned to capitalize on this massive and expanding audience. By fostering a vibrant community and enhancing player engagement, we are set to drive significant growth in the gaming sector.',
    isActive: true,
    isFounder: true,
    sortOrder: 1
  },
  {
    _id: 'team-002',
    _type: 'teamMember',
    _createdAt: '2023-01-01T00:00:00Z',
    _updatedAt: '2024-01-01T00:00:00Z',
    _rev: 'rev-002',
    name: 'Hemanth Joseph',
    position: 'Chief Security Officer',
    department: 'leadership',
    bio: 'As Chief Security Officer and Founding Member, I bring deep cybersecurity expertise combined with startup leadership to GAMERS TAG. My mission is to build the most secure gaming platform while driving innovation that transforms how the world views gaming. I believe that security is not just protection—it\'s the foundation that enables limitless possibilities for gamers worldwide.',
    shortBio: 'Securing the Gaming Revolution with Innovation',
    personalDetails: {
      aboutMe: 'I\'m a cybersecurity expert and startup veteran who believes that the future of gaming lies in creating secure, innovative ecosystems where gamers can thrive professionally. My background spans enterprise security, threat intelligence, and startup strategy, making me uniquely positioned to protect GAMERS TAG\'s revolutionary platform.',
      whatIDo: 'I architect comprehensive security frameworks that protect our platform without compromising user experience. From threat modeling to incident response, I ensure that every aspect of GAMERS TAG meets the highest security standards. I also drive strategic initiatives that position security as a competitive advantage.',
      mission: 'To build the world\'s most secure gaming platform that enables professional gaming careers while setting new industry standards for cybersecurity in the gaming sector.'
    },
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-hemanth', _type: 'reference' } },
    linkedinUrl: 'https://www.hemanthjoseph.com/',
    website: 'https://www.hemanthjoseph.com/',
    expertise: [
      'Cybersecurity Architecture',
      'Threat Intelligence & Analysis',
      'Security Risk Management',
      'Incident Response & Recovery',
      'Compliance & Governance',
      'Startup Security Strategy',
      'Gaming Platform Security',
      'Zero Trust Architecture',
      'Cloud Security',
      'Identity & Access Management',
      'Security Automation',
      'Penetration Testing',
      'Security Awareness Training',
      'Business Continuity Planning',
      'Strategic Security Leadership'
    ],
    education: [
      'Advanced Cybersecurity Certifications (CISSP, CISM, CEH)',
      'Startup Leadership & Strategy Programs',
      'Cloud Security Architecture Certifications',
      'Information Security Management',
      'Business Administration with Security Focus'
    ],
    certifications: [
      'Certified Information Systems Security Professional (CISSP)',
      'Certified Information Security Manager (CISM)',
      'Certified Ethical Hacker (CEH)',
      'AWS Security Specialty',
      'Cloud Security Alliance (CSA) Certifications',
      'ISO 27001 Lead Auditor'
    ],
    achievements: [
      'Built Security Framework for 50+ Gaming Products',
      'Zero Security Incidents in Production Systems',
      'Implemented Industry-First Gaming Security Standards',
      'Led Security for $100M+ Gaming Transactions',
      'Created Security Training Programs for 350+ Team Members',
      'Developed Proprietary Threat Detection Algorithms',
      'Speaking Expert at Cybersecurity Conferences',
      'Published Security Research in Gaming Industry'
    ],
    quote: 'The gaming industry stands at the precipice of unprecedented transformation. At GAMERS TAG, we envision a future where every gamer transcends traditional boundaries, becoming recognized professionals in a secure, innovative ecosystem. Our mission is not just to participate in this revolution, but to lead it with cutting-edge security and visionary leadership that protects dreams while enabling limitless possibilities.',
    isActive: true,
    isFounder: true,
    sortOrder: 2
  },
  {
    _id: 'team-003',
    _type: 'teamMember',
    _createdAt: '2023-01-01T00:00:00Z',
    _updatedAt: '2024-01-01T00:00:00Z',
    _rev: 'rev-003',
    name: 'Adesh Kumar',
    position: 'Director of Engineering & Founding Member',
    department: 'leadership',
    bio: 'As Director of Engineering and Founding Member from IIT Guwahati with ex-Amazon experience, I architect the technological backbone of GAMERS TAG. My expertise spans AI, Web3, blockchain, and full-stack development, creating revolutionary gaming solutions that push the boundaries of what\'s possible. I believe in building not just software, but experiences that transform how millions of gamers interact with technology.',
    shortBio: 'IIT Engineer Building Next-Gen Gaming Technology',
    personalDetails: {
      aboutMe: 'I\'m an IIT Guwahati graduate and ex-Amazon engineer who\'s passionate about creating technology that changes lives. My journey from competitive programming to enterprise engineering at Amazon, and now to founding GAMERS TAG, has been driven by the belief that great engineering can democratize opportunities for millions of gamers worldwide.',
      whatIDo: 'I lead the engineering vision for GAMERS TAG, architecting scalable systems that handle millions of users while maintaining performance excellence. I work across the full technology stack—from AI algorithms that power personalized experiences to blockchain integrations that ensure fair gaming economies. My focus is on building patentable innovations that set new industry standards.',
      mission: 'To engineer the most advanced gaming platform that combines AI, Web3, and cutting-edge technology to create unprecedented opportunities for the global gaming community.'
    },
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-adesh', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/adeshkpatra/',
    expertise: [
      'AI & Machine Learning Engineering',
      'Web3 & Blockchain Development',
      'Cryptocurrency & DeFi Systems',
      'Full Stack Architecture',
      'Distributed Systems Design',
      'Cloud Computing & DevOps',
      'Microservices Architecture',
      'Real-time Gaming Systems',
      'Data Engineering & Analytics',
      'API Design & Development',
      'Performance Optimization',
      'Scalable Backend Systems',
      'Mobile App Development',
      'Database Architecture',
      'Engineering Leadership'
    ],
    education: [
      'IIT Guwahati - B.Tech Computer Science Engineering (2018-2022)',
      'Advanced AI/ML Specialization - Stanford Online',
      'Blockchain Development Certification - Ethereum Foundation',
      'AWS Solutions Architect Professional',
      'Google Cloud Professional Developer'
    ],
    experience: [
      'Ex-Amazon Software Development Engineer Intern',
      'Lead Engineer - Multiple Startup Projects',
      'Full Stack Developer - Enterprise Applications',
      'AI Research - Academic Projects at IIT Guwahati',
      'Open Source Contributor - Various Gaming Projects'
    ],
    achievements: [
      'Led Engineering for 24+ Game Tech Products',
      'Architected Systems Handling 1M+ Concurrent Users',
      'Developed 15+ Patentable Gaming Algorithms',
      'Built AI Models with 95%+ Accuracy for Gaming Analytics',
      'Created Blockchain Gaming Economy Supporting $10M+ Transactions',
      'Optimized System Performance by 300%+',
      'Led Engineering Team of 50+ Developers',
      'Published Research on Gaming AI at Top Conferences',
      'Winner - Multiple National Coding Competitions',
      'IIT Guwahati Dean\'s List Scholar'
    ],
    technologies: [
      'Python, JavaScript, TypeScript, Java, C++',
      'React, Node.js, Django, Flask, FastAPI',
      'AWS, Google Cloud, Azure, Kubernetes, Docker',
      'PostgreSQL, MongoDB, Redis, Elasticsearch',
      'TensorFlow, PyTorch, Scikit-learn',
      'Ethereum, Solidity, Web3.js, Polygon',
      'Git, CI/CD, Jenkins, GitHub Actions',
      'Microservices, GraphQL, REST APIs'
    ],
    quote: 'Building a highly engineered product with multiple patentable algorithms and latest technology. The interaction of AI and SaaS complex algorithms makes GAMERS TAG a unique and sensational product in gaming, setting new standards for technical excellence. We\'re not just building software—we\'re engineering the future of how gamers connect, compete, and create value in the digital economy.',
    isActive: true,
    isFounder: true,
    sortOrder: 3
  },
  {
    _id: 'team-004',
    _type: 'teamMember',
    _createdAt: '2023-01-01T00:00:00Z',
    _updatedAt: '2024-01-01T00:00:00Z',
    _rev: 'rev-004',
    name: 'Harsh',
    position: 'Lead Front-end Developer',
    department: 'engineering',
    bio: 'As Chief Technology Officer and Founding Member, I lead the technological revolution at GAMERS TAG with a focus on building scalable, high-performance gaming infrastructure. My expertise in modern software architecture, cloud technologies, and distributed systems enables us to create gaming experiences that can scale to millions of users while maintaining exceptional performance and reliability.',
    shortBio: 'Architecting the Future of Gaming Technology',
    personalDetails: {
      aboutMe: 'I\'m a technology leader passionate about creating scalable systems that can handle the demands of modern gaming. My journey from frontend development to becoming CTO has been driven by the belief that great technology should be invisible to users while enabling extraordinary experiences. I combine deep technical knowledge with strategic vision to build the infrastructure that powers GAMERS TAG.',
      whatIDo: 'I oversee the entire technology stack at GAMERS TAG, from frontend user experiences to backend infrastructure. I lead our engineering teams in developing innovative solutions that handle real-time gaming interactions, massive data processing, and seamless user experiences. My focus is on building technology that scales effortlessly and performs flawlessly under any load.',
      mission: 'To build the most advanced, scalable gaming technology platform that enables millions of gamers worldwide to connect, compete, and thrive in the digital gaming economy.'
    },
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-harsh', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/harsh-singh-639316291/',
    expertise: [
      'Technical Leadership & Strategy',
      'Scalable Software Architecture',
      'Cloud Computing & DevOps',
      'Distributed Systems Design',
      'Frontend Development Excellence',
      'Real-time Gaming Infrastructure',
      'Performance Optimization',
      'Team Leadership & Mentoring',
      'Technology Innovation',
      'System Integration',
      'Database Architecture',
      'API Design & Development',
      'Mobile Application Development',
      'Gaming Platform Development',
      'Agile Development Methodologies'
    ],
    education: [
      'Computer Science Engineering - B.Tech',
      'Advanced Cloud Architecture Certifications',
      'AWS Solutions Architect Professional',
      'Google Cloud Professional Developer',
      'Kubernetes Certified Administrator',
      'Advanced React & JavaScript Certifications'
    ],
    technologies: [
      'React, TypeScript, JavaScript, HTML5, CSS3',
      'Node.js, Express.js, Python, Java',
      'AWS, Google Cloud, Azure, Docker, Kubernetes',
      'PostgreSQL, MongoDB, Redis, Firebase',
      'GraphQL, REST APIs, WebSocket',
      'Git, CI/CD, Jenkins, GitHub Actions',
      'Terraform, Infrastructure as Code',
      'Monitoring: Prometheus, Grafana, ELK Stack'
    ],
    achievements: [
      'Built Gaming Infrastructure Supporting 1M+ Users',
      'Led Development of 24+ Gaming Technology Products',
      'Achieved 99.9% Uptime for Critical Gaming Systems',
      'Optimized System Performance by 400%+',
      'Created Frontend Architecture Used by 350+ Developers',
      'Implemented Real-time Gaming Features with <50ms Latency',
      'Led Technical Teams Across 15+ Countries',
      'Architected Microservices Handling 10M+ API Calls/Day',
      'Developed Progressive Web Apps with 95%+ Performance Scores',
      'Published Technical Articles on Gaming Architecture'
    ],
    projects: [
      'GAMERS TAG Super Platform - Lead Architect',
      'Real-time Gaming Communication System',
      'Scalable User Authentication & Authorization',
      'Gaming Analytics & Data Processing Pipeline',
      'Mobile Gaming Companion Applications',
      'Cross-platform Gaming Integration APIs'
    ],
    quote: 'At GAMERS TAG, we are not just building a platform; we are architecting the technological foundation for the future of gaming. Our commitment to cutting-edge technology and scalable architecture ensures that gamers worldwide experience unprecedented performance and innovation. Every line of code we write is designed to empower the next generation of gaming experiences.',
    isActive: true,
    isFounder: true,
    sortOrder: 4
  },
  {
    _id: 'team-005',
    _type: 'teamMember',
    _createdAt: '2023-01-01T00:00:00Z',
    _updatedAt: '2024-01-01T00:00:00Z',
    _rev: 'rev-005',
    name: 'Paul',
    position: 'Director of Operations',
    department: 'leadership',
    bio: 'As Chief Strategy Officer and Founding Member, I drive the strategic vision that positions GAMERS TAG at the forefront of the global gaming revolution. My expertise spans market analysis, business development, strategic partnerships, and global expansion initiatives that transform how the gaming industry operates. I believe in creating strategies that not only drive growth but also create lasting value for the entire gaming ecosystem.',
    shortBio: 'Strategic Visionary Driving Gaming Industry Transformation',
    personalDetails: {
      aboutMe: 'I\'m a strategic leader with a passion for identifying and capitalizing on transformative opportunities in the gaming industry. My background combines deep market analysis with hands-on business development experience, enabling me to craft strategies that drive sustainable growth while creating meaningful impact for gamers worldwide.',
      whatIDo: 'I lead strategic planning and execution at GAMERS TAG, focusing on market expansion, partnership development, and competitive positioning. I work closely with industry leaders, investors, and gaming communities to identify opportunities that align with our mission of revolutionizing the gaming experience. My approach combines data-driven analysis with innovative thinking to create strategies that set new industry standards.',
      mission: 'To position GAMERS TAG as the global leader in gaming technology while creating strategies that elevate the entire gaming industry and unlock unprecedented opportunities for gamers worldwide.'
    },
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-paul', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/paul-dickinson-038511190/',
    expertise: [
      'Strategic Planning & Execution',
      'Business Development & Growth',
      'Market Analysis & Intelligence',
      'Global Expansion Strategy',
      'Partnership Development',
      'Competitive Intelligence',
      'Investment Strategy',
      'Gaming Industry Analysis',
      'Digital Transformation',
      'Revenue Optimization',
      'Brand Strategy & Positioning',
      'Stakeholder Management',
      'Gaming Economics & Monetization',
      'International Business Development',
      'Strategic Communications'
    ],
    education: [
      'Master of Business Administration (MBA) - Strategic Management',
      'Bachelor of Business Administration - International Business',
      'Strategic Leadership Certificate - Harvard Business School',
      'Digital Strategy Certification - MIT Sloan',
      'Gaming Industry Analysis Certification',
      'Global Market Entry Strategy - Wharton'
    ],
    experience: [
      'Chief Strategy Officer - GAMERS TAG (Founding Member)',
      'Senior Business Development Manager - Gaming Industry',
      'Strategic Consultant - Technology Startups',
      'Market Research Analyst - Entertainment Sector',
      'International Business Development - Multiple Industries'
    ],
    achievements: [
      'Developed Strategic Framework for $500M+ Gaming Market',
      'Led Partnerships Generating $50M+ in Revenue Potential',
      'Architected Global Expansion Strategy for 25+ Countries',
      'Created Gaming Industry Analysis Used by 100+ Companies',
      'Negotiated Strategic Alliances with Top Gaming Companies',
      'Built Market Intelligence Systems Tracking 1000+ Competitors',
      'Developed Investment Strategy Attracting $25M+ Funding Interest',
      'Led Strategic Planning for 24+ Gaming Products Launch',
      'Created Partnership Network Spanning 15+ Countries',
      'Published Strategic Insights Featured in Gaming Industry Reports'
    ],
    specializations: [
      'Gaming Market Dynamics & Trends',
      'Esports Industry Strategy',
      'Gaming Technology Partnerships',
      'International Market Entry',
      'Gaming Monetization Models',
      'Community Building Strategies',
      'Gaming Platform Ecosystems',
      'Digital Entertainment Analytics'
    ],
    quote: 'The gaming industry represents one of the most dynamic and rapidly evolving markets globally. At GAMERS TAG, we are strategically positioned to capture unprecedented opportunities and drive meaningful transformation that benefits every stakeholder in the gaming ecosystem. Our strategy is not just about growth—it\'s about creating a future where gaming becomes the foundation for global digital entertainment and professional opportunities.',
    isActive: true,
    isFounder: true,
    sortOrder: 5
  },
  {
    _id: 'team-006',
    _type: 'teamMember',
    _createdAt: '2023-01-01T00:00:00Z',
    _updatedAt: '2024-01-01T00:00:00Z',
    _rev: 'rev-006',
    name: 'Monish Goutham',
    position: 'Lead Marketing Manager',
    department: 'marketing',
    bio: 'I am currently pursuing MBA at the Indian Institute of Management Trichy. I hold a B.E. in Computer Science from BNMIT, where I worked on projects combining my passion for sports and games, curiosity in machine learning-based prediction models. After graduation, I joined Oracle Health as a System Engineer, gaining valuable exposure to the corporate world. My primary role involved managing Windows servers, ensuring their uptime, troubleshooting issues, and performing root cause analysis to maintain operational efficiency. This experience honed my technical expertise and problem-solving skills. Additionally, running a successful YouTube channel taught me how to view challenges from a customer\'s perspective and build strong engagement strategies. Inspired by this, I am now eager to explore the business side of decision-making—understanding the \'why\' behind strategic choices and their commercial impact. With a strong foundation in technology and a growing understanding of business, I aspire to transition into product management, where I can drive impactful decisions, bridge the gap between technology and customer needs, and create value for businesses and their users.',
    shortBio: 'IIM Trichy PGPM\'26 | Media Relations Coordinator | Ex-Oracle Health | YouTube Content Creator (75k+) (50M+ Views) | ITIL 4',
    personalDetails: {
      aboutMe: 'I am a dynamic marketing professional currently pursuing MBA at IIM Trichy with a unique blend of technical expertise and content creation experience. My journey from computer science engineering to Oracle Health and now to leading marketing initiatives at GAMERS TAG represents my passion for bridging technology and customer engagement.',
      whatIDo: 'I lead marketing strategies that combine data-driven insights with creative storytelling. My YouTube channel experience with 75k+ subscribers and 50M+ views gives me deep understanding of digital audience engagement, while my technical background helps me communicate complex gaming concepts effectively.',
      mission: 'To revolutionize gaming marketing by creating authentic connections between technology and community, driving growth through innovative digital strategies and customer-centric approaches.'
    },
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-monish', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/monish-goutham/?originalSubdomain=in',
    expertise: [
      'Digital Marketing Strategy',
      'Content Creation & Strategy',
      'YouTube Marketing & Growth',
      'Media Relations & Communications',
      'Technical Marketing',
      'Product Management Transition',
      'Customer Engagement Strategies',
      'Data-Driven Marketing',
      'System Engineering (Oracle Health)',
      'Windows Server Management',
      'Machine Learning Applications',
      'Gaming Industry Marketing',
      'Social Media Strategy',
      'Brand Building & Positioning',
      'Performance Marketing'
    ],
    education: [
      'IIM Trichy - PGPM (MBA) 2024-2026',
      'BNMIT - B.E. Computer Science Engineering',
      'ITIL 4 Foundation Certification',
      'Digital Marketing Certifications',
      'Content Strategy & Creation Programs'
    ],
    experience: [
      'Lead Marketing Manager - GAMERS TAG',
      'System Engineer - Oracle Health',
      'YouTube Content Creator (75k+ Subscribers, 50M+ Views)',
      'Media Relations Coordinator',
      'Technical Projects - Machine Learning Prediction Models'
    ],
    achievements: [
      'Built YouTube Channel to 75k+ Subscribers',
      'Generated 50M+ Video Views',
      'Led Marketing Campaigns for Gaming Products',
      'Successfully Managed Oracle Health Server Infrastructure',
      'Developed ML-based Sports/Gaming Prediction Models',
      'ITIL 4 Certified Professional',
      'Top Performer at Oracle Health',
      'Media Relations Excellence',
      'Technical Marketing Innovation',
      'Customer Engagement Growth Expert'
    ],
    technologies: [
      'Digital Marketing Platforms',
      'YouTube Studio & Analytics',
      'Social Media Management Tools',
      'Windows Server Administration',
      'Machine Learning Frameworks',
      'Data Analytics & Insights',
      'Content Management Systems',
      'Marketing Automation Tools'
    ],
    quote: 'Marketing in the gaming industry isn\'t just about promotion—it\'s about building authentic communities and creating experiences that resonate with gamers\' passions. My technical background combined with content creation expertise allows me to bridge the gap between complex gaming technology and meaningful customer engagement.',
    isActive: true,
    isFounder: false,
    sortOrder: 6
  },

  // Other Team Members - All authentic GAMERS TAG team members
  {
    _id: 'team-006',
    _type: 'teamMember',
    name: 'Tintu Tomy',
    position: 'Core Team Member',
    department: 'core',
    bio: 'Core team member contributing to GAMERS TAG\'s mission and growth',
    shortBio: 'Core team leadership',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-tintu', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/tintu-tomy-93655a24',
    expertise: ['Team Leadership', 'Operations', 'Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 6
  },
  {
    _id: 'team-007',
    _type: 'teamMember',
    name: 'Nithin George',
    position: 'Core Tech Member',
    department: 'engineering',
    bio: 'Core technology member driving technical excellence at GAMERS TAG',
    shortBio: 'Technical leadership and innovation',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-nithin', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/nithin-george-308a9458/',
    expertise: ['Software Engineering', 'Technical Leadership', 'System Architecture'],
    isActive: true,
    isFounder: false,
    sortOrder: 7
  },
  {
    _id: 'team-008',
    _type: 'teamMember',
    name: 'Fathima Nihma',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager overseeing talent management and organizational development',
    shortBio: 'Building great teams',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-fathima', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/fathima-nihma',
    expertise: ['Human Resources', 'Talent Management', 'Team Building'],
    isActive: true,
    isFounder: false,
    sortOrder: 8
  },
  {
    _id: 'team-009',
    _type: 'teamMember',
    name: 'Mohd Amber Rizvi',
    position: 'Core Tech Member',
    department: 'engineering',
    bio: 'Core technology member contributing to technical development',
    shortBio: 'Technical excellence and innovation',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-amber', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/mohd-amber-rizvi-93a55a201',
    expertise: ['Software Development', 'Technical Innovation', 'System Design'],
    isActive: true,
    isFounder: false,
    sortOrder: 9
  },
  {
    _id: 'team-010',
    _type: 'teamMember',
    name: 'Shivansh Verma',
    position: 'Core Tech Member',
    department: 'engineering',
    bio: 'Core technology member driving technical innovation',
    shortBio: 'Technical leadership and development',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-shivansh', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/meet-shivanshverma',
    expertise: ['Software Engineering', 'Technical Strategy', 'Product Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 10
  },
  {
    _id: 'team-011',
    _type: 'teamMember',
    name: 'Ditto Johnson',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager building GAMERS TAG\'s online presence and community engagement',
    shortBio: 'Building gaming communities online',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-ditto', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/ditto-johnson-941267249',
    expertise: ['Social Media Marketing', 'Community Management', 'Content Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 11
  },
  {
    _id: 'team-012',
    _type: 'teamMember',
    name: 'Jayandra Todawat',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to GAMERS TAG\'s technical development and platform features',
    shortBio: 'Building innovative gaming solutions',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-jayandra', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/jayndra-todawat',
    expertise: ['Software Development', 'Web Development', 'Gaming Platforms'],
    isActive: true,
    isFounder: false,
    sortOrder: 12
  },
  {
    _id: 'team-013',
    _type: 'teamMember',
    name: 'Sakshi Dhoni',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer working on GAMERS TAG\'s platform development and technical features',
    shortBio: 'Software development excellence',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-sakshi', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/sakshidhoni',
    expertise: ['Software Development', 'Programming', 'Technical Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 13
  },
  {
    _id: 'team-014',
    _type: 'teamMember',
    name: 'Himani Sharma',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager focusing on talent acquisition and team development',
    shortBio: 'Talent management and team growth',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-himani', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/himanisharma062',
    expertise: ['Human Resources', 'Talent Acquisition', 'Team Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 14
  },
  {
    _id: 'team-015',
    _type: 'teamMember',
    name: 'Suhitha Suresh',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager overseeing employee relations and organizational culture',
    shortBio: 'Building organizational culture',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-suhitha', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/suhitha1722',
    expertise: ['Human Resources', 'Employee Relations', 'Culture Building'],
    isActive: true,
    isFounder: false,
    sortOrder: 15
  },
  {
    _id: 'team-016',
    _type: 'teamMember',
    name: 'Rishitha Jain',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager focusing on employee development and organizational growth',
    shortBio: 'Employee development specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-rishitha', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/rishita-jain-24890b30a',
    expertise: ['Human Resources', 'Employee Development', 'Organizational Growth'],
    isActive: true,
    isFounder: false,
    sortOrder: 16
  },
  {
    _id: 'team-017',
    _type: 'teamMember',
    name: 'Sukhmani Kaur',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager specializing in talent management and team coordination',
    shortBio: 'Talent management expert',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-sukhmani', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/itssukhmanikaur',
    expertise: ['Human Resources', 'Talent Management', 'Team Coordination'],
    isActive: true,
    isFounder: false,
    sortOrder: 17
  },
  {
    _id: 'team-018',
    _type: 'teamMember',
    name: 'Shamil Mohamed',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager driving GAMERS TAG\'s brand identity and market positioning',
    shortBio: 'Brand strategy and identity',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-shamil', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/muhammed-shamil-thottungal',
    expertise: ['Brand Management', 'Marketing Strategy', 'Brand Identity'],
    isActive: true,
    isFounder: false,
    sortOrder: 18
  },
  {
    _id: 'team-019',
    _type: 'teamMember',
    name: 'Dibin Jose Vadakkan',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst providing strategic financial insights and analysis',
    shortBio: 'Strategic financial analysis',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-dibin', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/dibin-jose-vadakkan-69109179',
    expertise: ['Financial Analysis', 'Strategic Planning', 'Financial Insights'],
    isActive: true,
    isFounder: false,
    sortOrder: 19
  },
  {
    _id: 'team-020',
    _type: 'teamMember',
    name: 'Arjun Gopi K',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to GAMERS TAG\'s platform development',
    shortBio: 'Platform development specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-arjun', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/arjun-gopi-k-324178253',
    expertise: ['Software Development', 'Platform Engineering', 'Technical Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 20
  },
  // Continue with more team members from the authentic list
  {
    _id: 'team-021',
    _type: 'teamMember',
    name: 'Haniya Abdul Rahman',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating visual experiences for GAMERS TAG',
    shortBio: 'Creative visual design',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-haniya', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/haniya-ar',
    expertise: ['UI/UX Design', 'Visual Design', 'Creative Direction'],
    isActive: true,
    isFounder: false,
    sortOrder: 21
  },
  {
    _id: 'team-022',
    _type: 'teamMember',
    name: 'Manish Verma',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to platform development and technical solutions',
    shortBio: 'Technical development expert',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-manish', _type: 'reference' } },
    linkedinUrl: '',
    expertise: ['Software Development', 'Programming', 'Technical Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 22
  },
  {
    _id: 'team-023',
    _type: 'teamMember',
    name: 'Ankita Soni',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer working on innovative gaming platform features',
    shortBio: 'Platform feature development',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-ankita', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/aankita-soni',
    expertise: ['Software Development', 'Feature Development', 'Gaming Platforms'],
    isActive: true,
    isFounder: false,
    sortOrder: 23
  },
  {
    _id: 'team-024',
    _type: 'teamMember',
    name: 'Jilha Jose',
    position: 'App Tester',
    department: 'qa',
    bio: 'App Tester ensuring quality and performance of GAMERS TAG applications',
    shortBio: 'Quality assurance specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-jilha', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/jilha-jos/',
    expertise: ['Quality Assurance', 'App Testing', 'Performance Testing'],
    isActive: true,
    isFounder: false,
    sortOrder: 24
  },
  {
    _id: 'team-025',
    _type: 'teamMember',
    name: 'Ardra Shashidharan',
    position: 'App Tester',
    department: 'qa',
    bio: 'App Tester focused on application quality and user experience testing',
    shortBio: 'User experience testing expert',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-ardra', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/ardra-sasidharan-05a861211',
    expertise: ['Quality Assurance', 'User Experience Testing', 'Mobile Testing'],
    isActive: true,
    isFounder: false,
    sortOrder: 25
  },
  {
    _id: 'team-026',
    _type: 'teamMember',
    name: 'Aiswarya Madhu',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager building community engagement and brand presence',
    shortBio: 'Community engagement specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-aiswarya', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/vallathaiswarya',
    expertise: ['Social Media Marketing', 'Community Building', 'Brand Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 26
  },
  {
    _id: 'team-027',
    _type: 'teamMember',
    name: 'Gautam Krishna K',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager driving digital marketing and online presence',
    shortBio: 'Digital marketing strategist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-gautam', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/ACoAAEQ2Et4B8sLMLpi2zVd6IxWnwojTH8EyK-s',
    expertise: ['Social Media Strategy', 'Digital Marketing', 'Content Creation'],
    isActive: true,
    isFounder: false,
    sortOrder: 27
  },
  {
    _id: 'team-028',
    _type: 'teamMember',
    name: 'Aditya Rawat',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer building scalable solutions for GAMERS TAG platform',
    shortBio: 'Scalable solutions developer',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-aditya', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/theadityarawat',
    expertise: ['Software Development', 'Scalable Architecture', 'Platform Engineering'],
    isActive: true,
    isFounder: false,
    sortOrder: 28
  },
  {
    _id: 'team-029',
    _type: 'teamMember',
    name: 'Nithin Dhawane',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating user-centered design solutions',
    shortBio: 'User-centered design specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-nithin-d', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/nitin-dhawane-39b07515a',
    expertise: ['UI/UX Design', 'User Research', 'Design Systems'],
    isActive: true,
    isFounder: false,
    sortOrder: 29
  },
  {
    _id: 'team-030',
    _type: 'teamMember',
    name: 'Kevin George',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member focused on interactive and visual design',
    shortBio: 'Interactive design expert',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-kevin', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/kevin-george-58b5701a1',
    expertise: ['Interactive Design', 'Visual Design', 'User Interface'],
    isActive: true,
    isFounder: false,
    sortOrder: 30
  },
  {
    _id: 'team-031',
    _type: 'teamMember',
    name: 'Jeethu Singh',
    position: 'Esports Manager',
    department: 'esports',
    bio: 'Esports Manager leading competitive gaming initiatives and tournaments',
    shortBio: 'Competitive gaming leader',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-jeethu', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/jeetu-singh-574665292',
    expertise: ['Esports Management', 'Tournament Organization', 'Competitive Gaming'],
    isActive: true,
    isFounder: false,
    sortOrder: 31
  },
  {
    _id: 'team-032',
    _type: 'teamMember',
    name: 'Indrajith Ajith',
    position: 'Esports Manager',
    department: 'esports',
    bio: 'Esports Manager driving competitive gaming strategy and community building',
    shortBio: 'Esports strategy specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-indrajith', _type: 'reference' } },
    linkedinUrl: '',
    expertise: ['Esports Strategy', 'Community Management', 'Gaming Events'],
    isActive: true,
    isFounder: false,
    sortOrder: 32
  },
  {
    _id: 'team-033',
    _type: 'teamMember',
    name: 'Mariya Joshy',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst providing strategic financial planning and analysis',
    shortBio: 'Financial planning expert',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-mariya', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/mariya-joshy-97bba4222',
    expertise: ['Financial Analysis', 'Strategic Planning', 'Budget Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 33
  },
  {
    _id: 'team-034',
    _type: 'teamMember',
    name: 'Abhishek S Nair',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst specializing in financial modeling and business analysis',
    shortBio: 'Financial modeling specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-abhishek', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/abhishek-s-nair50',
    expertise: ['Financial Modeling', 'Business Analysis', 'Data Analytics'],
    isActive: true,
    isFounder: false,
    sortOrder: 34
  },
  {
    _id: 'team-035',
    _type: 'teamMember',
    name: 'Abhinaya R',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager creating engaging content and managing online communities',
    shortBio: 'Content creation specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-abhinaya', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/abhinaya-ravic',
    expertise: ['Content Creation', 'Social Media Strategy', 'Community Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 35
  },
  // Adding the rest of the authentic team members
  {
    _id: 'team-036',
    _type: 'teamMember',
    name: 'Naman Sharma',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager driving brand awareness and digital engagement',
    shortBio: 'Brand awareness specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-naman', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/naman-sharma-682189244',
    expertise: ['Social Media Marketing', 'Brand Awareness', 'Digital Engagement'],
    isActive: true,
    isFounder: false,
    sortOrder: 36
  },
  {
    _id: 'team-037',
    _type: 'teamMember',
    name: 'Utkarsh Kumar Upadhyay',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer working on advanced technical solutions and platform enhancement',
    shortBio: 'Advanced technical solutions',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-utkarsh', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/utkarsh-kumar-upadhyay-18685b24a',
    expertise: ['Software Development', 'Technical Solutions', 'Platform Enhancement'],
    isActive: true,
    isFounder: false,
    sortOrder: 37
  },
  {
    _id: 'team-038',
    _type: 'teamMember',
    name: 'Dipankar Upadhyaya',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to backend systems and application architecture',
    shortBio: 'Backend systems specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-dipankar', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/dipankar-upadhyaya-26618b238',
    expertise: ['Backend Development', 'System Architecture', 'Application Design'],
    isActive: true,
    isFounder: false,
    sortOrder: 38
  },
  {
    _id: 'team-039',
    _type: 'teamMember',
    name: 'Alen Joshy',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member specializing in creative visual solutions',
    shortBio: 'Creative visual solutions',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-alen', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/alen-joshy-4025a41bb',
    expertise: ['Visual Design', 'Creative Solutions', 'Brand Design'],
    isActive: true,
    isFounder: false,
    sortOrder: 39
  },
  {
    _id: 'team-040',
    _type: 'teamMember',
    name: 'Shubham Chintal',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor creating engaging visual content for GAMERS TAG',
    shortBio: 'Engaging visual content creator',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-shubham-c', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/shubham-chintal-254683292',
    expertise: ['Video Editing', 'Visual Content', 'Motion Graphics'],
    isActive: true,
    isFounder: false,
    sortOrder: 40
  },
  {
    _id: 'team-041',
    _type: 'teamMember',
    name: 'Ahammed Habeebi',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member focused on user experience and interface design',
    shortBio: 'User experience designer',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-ahammed', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/ahammed-habeebi-b4997021',
    expertise: ['User Experience', 'Interface Design', 'Design Systems'],
    isActive: true,
    isFounder: false,
    sortOrder: 41
  },
  {
    _id: 'team-042',
    _type: 'teamMember',
    name: 'Philip George',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager developing brand strategy and market positioning',
    shortBio: 'Brand strategy developer',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-philip', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/philip-george-408786216',
    expertise: ['Brand Strategy', 'Market Positioning', 'Brand Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 42
  },
  {
    _id: 'team-043',
    _type: 'teamMember',
    name: 'Amruth',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager driving brand innovation and market expansion',
    shortBio: 'Brand innovation specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-amruth', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/amruth-n',
    expertise: ['Brand Innovation', 'Market Expansion', 'Creative Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 43
  },
  {
    _id: 'team-044',
    _type: 'teamMember',
    name: 'Shreyansh Khandelwal',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer building innovative features and technical solutions',
    shortBio: 'Innovative feature developer',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-shreyansh', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/shreyansh-khandelwal-383718165',
    expertise: ['Feature Development', 'Technical Innovation', 'Software Engineering'],
    isActive: true,
    isFounder: false,
    sortOrder: 44
  },
  {
    _id: 'team-045',
    _type: 'teamMember',
    name: 'Vaidant Sharma',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer specializing in platform optimization and performance',
    shortBio: 'Platform optimization expert',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-vaidant', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/vaidant-sharma-7435592a4',
    expertise: ['Platform Optimization', 'Performance Engineering', 'System Efficiency'],
    isActive: true,
    isFounder: false,
    sortOrder: 45
  },
  {
    _id: 'team-046',
    _type: 'teamMember',
    name: 'Prakhar Singh',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to full-stack development and system integration',
    shortBio: 'Full-stack development specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-prakhar', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/meet-prakhar-singh',
    expertise: ['Full-Stack Development', 'System Integration', 'API Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 46
  },
  {
    _id: 'team-047',
    _type: 'teamMember',
    name: 'Shivam Chouhan',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer working on scalable applications and modern technologies',
    shortBio: 'Scalable applications developer',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-shivam', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/shivam-chouhan',
    expertise: ['Scalable Applications', 'Modern Technologies', 'Software Architecture'],
    isActive: true,
    isFounder: false,
    sortOrder: 47
  },
  {
    _id: 'team-048',
    _type: 'teamMember',
    name: 'Swapnil Adsul',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on innovative gaming solutions and platform development',
    shortBio: 'Gaming solutions developer',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-swapnil', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/swapnil-adsul-139515230',
    expertise: ['Gaming Solutions', 'Platform Development', 'Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 48
  },
  {
    _id: 'team-049',
    _type: 'teamMember',
    name: 'Shubh Agrawal',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to technical excellence and code quality',
    shortBio: 'Technical excellence specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-shubh', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/shubhagarwal0704',
    expertise: ['Technical Excellence', 'Code Quality', 'Software Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 49
  },
  {
    _id: 'team-050',
    _type: 'teamMember',
    name: 'Aman Nurmhamad Mujawar',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer working on platform enhancement and technical innovation',
    shortBio: 'Platform enhancement specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-aman-m', _type: 'reference' } },
    linkedinUrl: '',
    expertise: ['Platform Enhancement', 'Technical Innovation', 'Software Engineering'],
    isActive: true,
    isFounder: false,
    sortOrder: 50
  },
  // Continuing with the final batch of authentic team members
  {
    _id: 'team-051',
    _type: 'teamMember',
    name: 'Suhani Goyal',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating innovative design solutions for gaming experiences',
    shortBio: 'Innovative design solutions',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-suhani', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/suhanieie',
    expertise: ['Design Innovation', 'Gaming UI/UX', 'Creative Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 51
  },
  {
    _id: 'team-052',
    _type: 'teamMember',
    name: 'Minnathullaa S',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member focusing on visual aesthetics and user interface design',
    shortBio: 'Visual aesthetics specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-minnathullaa', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/minnathullaa-s-664694242',
    expertise: ['Visual Design', 'UI Design', 'Design Aesthetics'],
    isActive: true,
    isFounder: false,
    sortOrder: 52
  },
  {
    _id: 'team-053',
    _type: 'teamMember',
    name: 'Abel Antony',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst providing comprehensive financial analysis and strategic insights',
    shortBio: 'Comprehensive financial analysis',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-abel', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/abel-antony-benny',
    expertise: ['Financial Analysis', 'Strategic Insights', 'Financial Planning'],
    isActive: true,
    isFounder: false,
    sortOrder: 53
  },
  {
    _id: 'team-054',
    _type: 'teamMember',
    name: 'Ranjima AR',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to software development and technical solutions',
    shortBio: 'Software development specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-ranjima', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/ranjima-ar',
    expertise: ['Software Development', 'Technical Solutions', 'Programming'],
    isActive: true,
    isFounder: false,
    sortOrder: 54
  },
  {
    _id: 'team-055',
    _type: 'teamMember',
    name: 'Aman Kumar',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer working on platform features and system development',
    shortBio: 'Platform features developer',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-aman-k', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/ACoAAEeg9S4Baj86sVm9R5LVUqfHjeMNEq0rcDA',
    expertise: ['Platform Features', 'System Development', 'Software Engineering'],
    isActive: true,
    isFounder: false,
    sortOrder: 55
  },
  {
    _id: 'team-056',
    _type: 'teamMember',
    name: 'Dumpala Pardha Saradhi',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer specializing in advanced programming and system architecture',
    shortBio: 'Advanced programming specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-pardha', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/pardha-saradhi-818a93254',
    expertise: ['Advanced Programming', 'System Architecture', 'Technical Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 56
  },
  {
    _id: 'team-057',
    _type: 'teamMember',
    name: 'Shivansh Shukla',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on programming excellence and innovative solutions',
    shortBio: 'Programming excellence specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-shivansh-s', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/shukla-programmer',
    expertise: ['Programming Excellence', 'Innovation', 'Software Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 57
  },
  {
    _id: 'team-058',
    _type: 'teamMember',
    name: 'Alen Joe Abey',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor creating compelling visual narratives and content',
    shortBio: 'Visual narratives creator',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-alen-joe', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/alen-joe-abey-50603a311',
    expertise: ['Video Editing', 'Visual Narratives', 'Content Creation'],
    isActive: true,
    isFounder: false,
    sortOrder: 58
  },
  {
    _id: 'team-059',
    _type: 'teamMember',
    name: 'Ayush Anand',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor specializing in dynamic content and visual storytelling',
    shortBio: 'Dynamic content specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-ayush', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/ACoAAD1vndIBXzxjlwOq_5zStBEHtDcexrwtHVw',
    expertise: ['Video Editing', 'Visual Storytelling', 'Dynamic Content'],
    isActive: true,
    isFounder: false,
    sortOrder: 59
  },
  {
    _id: 'team-060',
    _type: 'teamMember',
    name: 'Iti Jain',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager driving organizational development and employee engagement',
    shortBio: 'Organizational development specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-iti', _type: 'reference' } },
    linkedinUrl: '',
    expertise: ['Human Resources', 'Organizational Development', 'Employee Engagement'],
    isActive: true,
    isFounder: false,
    sortOrder: 60
  },
  {
    _id: 'team-061',
    _type: 'teamMember',
    name: 'Kartheek Chilukoti',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager focusing on talent development and team management',
    shortBio: 'Talent development expert',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-kartheek', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/kartheek-chilukoti-038185228',
    expertise: ['Talent Development', 'Team Management', 'HR Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 61
  },
  {
    _id: 'team-062',
    _type: 'teamMember',
    name: 'Poojitha Pasham',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager specializing in employee relations and HR operations',
    shortBio: 'Employee relations specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-poojitha', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/poojitha-pasham-2355652a1',
    expertise: ['Employee Relations', 'HR Operations', 'People Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 62
  },
  {
    _id: 'team-063',
    _type: 'teamMember',
    name: 'Butool Zehra Jafri',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager driving workforce development and organizational culture',
    shortBio: 'Workforce development specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-butool', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/butoolzehra30',
    expertise: ['Workforce Development', 'Organizational Culture', 'HR Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 63
  },
  {
    _id: 'team-064',
    _type: 'teamMember',
    name: 'Mannat Malhotra',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager focusing on talent acquisition and employee development',
    shortBio: 'Talent acquisition specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-mannat', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/mannat-malhotra-82900a216',
    expertise: ['Talent Acquisition', 'Employee Development', 'Recruitment Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 64
  },
  {
    _id: 'team-065',
    _type: 'teamMember',
    name: 'Saanvi Rana',
    position: 'Content Writer',
    department: 'content',
    bio: 'Content Writer creating engaging written content for GAMERS TAG',
    shortBio: 'Engaging content creator',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-saanvi', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/saanvi-rana-082843256/',
    expertise: ['Content Writing', 'Creative Writing', 'Digital Content'],
    isActive: true,
    isFounder: false,
    sortOrder: 65
  },
  {
    _id: 'team-066',
    _type: 'teamMember',
    name: 'Alina Joseph',
    position: 'Content Writer',
    department: 'content',
    bio: 'Content Writer specializing in gaming content and storytelling',
    shortBio: 'Gaming content specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-alina', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/alinajoseph08',
    expertise: ['Gaming Content', 'Storytelling', 'Content Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 66
  },
  {
    _id: 'team-067',
    _type: 'teamMember',
    name: 'Himanshu Gupta',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to technical innovation and platform development',
    shortBio: 'Technical innovation specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-himanshu', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/himanshu-gupta-33491b1ba',
    expertise: ['Technical Innovation', 'Platform Development', 'Software Engineering'],
    isActive: true,
    isFounder: false,
    sortOrder: 67
  },
  {
    _id: 'team-068',
    _type: 'teamMember',
    name: 'Anushka Sharma',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager building brand presence and community engagement',
    shortBio: 'Brand presence builder',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-anushka', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/anushkasharma2211/',
    expertise: ['Social Media Management', 'Brand Presence', 'Community Engagement'],
    isActive: true,
    isFounder: false,
    sortOrder: 68
  },
  {
    _id: 'team-069',
    _type: 'teamMember',
    name: 'Jen Joy',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst providing data-driven financial insights and analysis',
    shortBio: 'Data-driven financial insights',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-jen', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/jentjoy',
    expertise: ['Financial Analysis', 'Data Analytics', 'Financial Insights'],
    isActive: true,
    isFounder: false,
    sortOrder: 69
  },
  {
    _id: 'team-070',
    _type: 'teamMember',
    name: 'Neha Chandrasekaran',
    position: 'Content Writer',
    department: 'content',
    bio: 'Content Writer creating compelling narratives and digital content',
    shortBio: 'Compelling narratives creator',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-neha-c', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/neha-chandrasekaran',
    expertise: ['Content Writing', 'Digital Narratives', 'Creative Content'],
    isActive: true,
    isFounder: false,
    sortOrder: 70
  },
  // Adding the remaining authentic team members to complete the roster
  {
    _id: 'team-071',
    _type: 'teamMember',
    name: 'Arun Kumar',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor creating dynamic video content and visual experiences',
    shortBio: 'Dynamic video content creator',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-arun', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/arunkumar12533',
    expertise: ['Video Editing', 'Visual Effects', 'Content Production'],
    isActive: true,
    isFounder: false,
    sortOrder: 71
  },
  {
    _id: 'team-072',
    _type: 'teamMember',
    name: 'Muhammed Shahin',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager driving digital engagement and community growth',
    shortBio: 'Digital engagement specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-shahin', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/muhammed-shahin-u-52a444210',
    expertise: ['Social Media Strategy', 'Digital Engagement', 'Community Growth'],
    isActive: true,
    isFounder: false,
    sortOrder: 72
  },
  {
    _id: 'team-073',
    _type: 'teamMember',
    name: 'Simontika Das',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor specializing in creative video production and storytelling',
    shortBio: 'Creative video production specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-simontika', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/simontika-das-9607402a5',
    expertise: ['Video Production', 'Creative Storytelling', 'Visual Content'],
    isActive: true,
    isFounder: false,
    sortOrder: 73
  },
  {
    _id: 'team-074',
    _type: 'teamMember',
    name: 'Snehal Mathur',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating innovative visual designs and user experiences',
    shortBio: 'Innovative visual design specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-snehal', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/snehalmathur2005/',
    expertise: ['Visual Design', 'User Experience', 'Design Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 74
  },
  {
    _id: 'team-075',
    _type: 'teamMember',
    name: 'Nasrin K',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst providing strategic financial planning and business insights',
    shortBio: 'Strategic financial planning specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-nasrin', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/nasrin-k',
    expertise: ['Financial Planning', 'Business Analysis', 'Strategic Insights'],
    isActive: true,
    isFounder: false,
    sortOrder: 75
  },
  {
    _id: 'team-076',
    _type: 'teamMember',
    name: 'Jerin Mathew',
    position: 'Financial Analyst',
    department: 'finance',
    bio: 'Financial Analyst specializing in data analysis and financial modeling',
    shortBio: 'Data analysis and modeling specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-jerin', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/jerin-mathew-60214a1b9',
    expertise: ['Data Analysis', 'Financial Modeling', 'Business Intelligence'],
    isActive: true,
    isFounder: false,
    sortOrder: 76
  },
  {
    _id: 'team-077',
    _type: 'teamMember',
    name: 'Baishali Dey Sarkar',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor creating engaging multimedia content and visual narratives',
    shortBio: 'Multimedia content creator',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-baishali', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/baishali-dey-sarkar-663b6232a',
    expertise: ['Video Editing', 'Multimedia Content', 'Visual Storytelling'],
    isActive: true,
    isFounder: false,
    sortOrder: 77
  },
  {
    _id: 'team-078',
    _type: 'teamMember',
    name: 'Sonu Dabi',
    position: 'Video Editor',
    department: 'content',
    bio: 'Video Editor focused on creative content production and video optimization',
    shortBio: 'Creative content production specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-sonu', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/sonu-dabi',
    expertise: ['Video Production', 'Content Optimization', 'Creative Editing'],
    isActive: true,
    isFounder: false,
    sortOrder: 78
  },
  {
    _id: 'team-079',
    _type: 'teamMember',
    name: 'Zeeshan Siddiqui',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager driving brand strategy and market positioning for GAMERS TAG',
    shortBio: 'Brand strategy and positioning specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-zeeshan', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/zeeshan-siddiqui-a93197249',
    expertise: ['Brand Strategy', 'Market Positioning', 'Brand Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 79
  },
  {
    _id: 'team-080',
    _type: 'teamMember',
    name: 'Vamsi Karthik',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating user-centered design solutions and visual experiences',
    shortBio: 'User-centered design specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-vamsi', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/vamsi-karthik555',
    expertise: ['User-Centered Design', 'Visual Experience', 'Design Systems'],
    isActive: true,
    isFounder: false,
    sortOrder: 80
  },
  {
    _id: 'team-081',
    _type: 'teamMember',
    name: 'Shubham Kumar',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager focused on brand innovation and strategic marketing initiatives',
    shortBio: 'Brand innovation specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-shubham-k', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/shubham-kumar-6a4804211',
    expertise: ['Brand Innovation', 'Strategic Marketing', 'Marketing Initiatives'],
    isActive: true,
    isFounder: false,
    sortOrder: 81
  },
  {
    _id: 'team-082',
    _type: 'teamMember',
    name: 'Anusha Popat',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member specializing in creative design solutions and visual communication',
    shortBio: 'Creative design solutions specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-anusha', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/anusha-popat-b199802a5',
    expertise: ['Creative Design', 'Visual Communication', 'Design Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 82
  },
  {
    _id: 'team-083',
    _type: 'teamMember',
    name: 'Taniya Jahagirdar',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating innovative design concepts and user interfaces',
    shortBio: 'Innovative design concepts specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-taniya', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/ACoAADicdL8Bpq4GiOZsaxIwzeHWMKXIQeVJvc',
    expertise: ['Design Innovation', 'User Interface', 'Concept Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 83
  },
  {
    _id: 'team-084',
    _type: 'teamMember',
    name: 'Ojash Gupta',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to platform development and technical innovation',
    shortBio: 'Platform development specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-ojash', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/ojash-gupta-7a755b1bb',
    expertise: ['Platform Development', 'Technical Innovation', 'Software Engineering'],
    isActive: true,
    isFounder: false,
    sortOrder: 84
  },
  {
    _id: 'team-085',
    _type: 'teamMember',
    name: 'Subhiksha Prabakaran',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member focused on user experience design and design research',
    shortBio: 'User experience design specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-subhiksha', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/subhiksha-prabakaran-101475135',
    expertise: ['User Experience Design', 'Design Research', 'UX Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 85
  },
  {
    _id: 'team-086',
    _type: 'teamMember',
    name: 'Prakhar Jain',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer working on innovative software solutions and platform enhancement',
    shortBio: 'Innovative software solutions specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-prakhar-j', _type: 'reference' } },
    linkedinUrl: 'http://www.linkedin.com/in/peter1prakhar',
    expertise: ['Software Solutions', 'Platform Enhancement', 'Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 86
  },
  {
    _id: 'team-087',
    _type: 'teamMember',
    name: 'Sagar Sharma',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager driving comprehensive brand strategy and market development',
    shortBio: 'Comprehensive brand strategy specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-sagar', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/ACoAACl_Cg4BMmMq_3SCQncdNOrZrfsV045R91A',
    expertise: ['Brand Strategy', 'Market Development', 'Strategic Planning'],
    isActive: true,
    isFounder: false,
    sortOrder: 87
  },
  {
    _id: 'team-088',
    _type: 'teamMember',
    name: 'Monish Goutham',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager focused on brand growth and strategic marketing initiatives',
    shortBio: 'Brand growth specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-monish', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/ACoAAC9UoCoBDdcQJuuLc_6WGn_4oPxg0z8sDZ8',
    expertise: ['Brand Growth', 'Strategic Marketing', 'Marketing Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 88
  },
  {
    _id: 'team-089',
    _type: 'teamMember',
    name: 'Dhruv Goel',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to cutting-edge technology solutions and platform development',
    shortBio: 'Cutting-edge technology solutions specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-dhruv', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/dhruv1100',
    expertise: ['Technology Solutions', 'Platform Development', 'Software Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 89
  },
  {
    _id: 'team-090',
    _type: 'teamMember',
    name: 'Asjad Raza',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer working on advanced development projects and technical solutions',
    shortBio: 'Advanced development projects specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-asjad', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/vedasjad',
    expertise: ['Advanced Development', 'Technical Solutions', 'Project Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 90
  },
  {
    _id: 'team-091',
    _type: 'teamMember',
    name: 'Umit Vadgama',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design Team Member creating exceptional design experiences and visual solutions',
    shortBio: 'Exceptional design experiences specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-umit', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/umitvadgama/',
    expertise: ['Design Experience', 'Visual Solutions', 'Creative Design'],
    isActive: true,
    isFounder: false,
    sortOrder: 91
  },
  {
    _id: 'team-092',
    _type: 'teamMember',
    name: 'Sundharam',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to software development and platform optimization',
    shortBio: 'Software development and optimization specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-sundharam', _type: 'reference' } },
    linkedinUrl: '',
    expertise: ['Software Development', 'Platform Optimization', 'Technical Excellence'],
    isActive: true,
    isFounder: false,
    sortOrder: 92
  },
  {
    _id: 'team-093',
    _type: 'teamMember',
    name: 'Divyansh Gandotra',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on innovative development solutions and technical advancement',
    shortBio: 'Innovative development solutions specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-divyansh', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/divyansh-gandotra-625aa1276',
    expertise: ['Development Solutions', 'Technical Advancement', 'Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 93
  },
  {
    _id: 'team-094',
    _type: 'teamMember',
    name: 'Ganesh S',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer working on comprehensive software solutions and system development',
    shortBio: 'Comprehensive software solutions specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-ganesh', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/ganesh-s-34874924b',
    expertise: ['Software Solutions', 'System Development', 'Technical Implementation'],
    isActive: true,
    isFounder: false,
    sortOrder: 94
  },
  {
    _id: 'team-095',
    _type: 'teamMember',
    name: 'Himani Srivastava',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer specializing in software engineering and platform development',
    shortBio: 'Software engineering specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-himani-s', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/himani-srivastava',
    expertise: ['Software Engineering', 'Platform Development', 'Technical Solutions'],
    isActive: true,
    isFounder: false,
    sortOrder: 95
  },
  {
    _id: 'team-096',
    _type: 'teamMember',
    name: 'Utpal Tiwari',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to advanced software development and technical innovation',
    shortBio: 'Advanced software development specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-utpal', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/utpal-tiwari-b6ab10203',
    expertise: ['Software Development', 'Technical Innovation', 'Advanced Programming'],
    isActive: true,
    isFounder: false,
    sortOrder: 96
  },
  {
    _id: 'team-097',
    _type: 'teamMember',
    name: 'Sundaram Pandey',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer focused on platform engineering and software development excellence',
    shortBio: 'Platform engineering specialist',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-sundaram-p', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/sundaram-pandey-155043237',
    expertise: ['Platform Engineering', 'Software Development', 'Technical Excellence'],
    isActive: true,
    isFounder: false,
    sortOrder: 97
  }
];

// Create separate exports for compatibility
export const coreTeamMembers = allAuthenticTeamMembers.filter(member => member.isFounder);
export const otherTeamMembers = allAuthenticTeamMembers.filter(member => !member.isFounder);
export const demoTeamMembers = allAuthenticTeamMembers;

// Use the authentic team data as the main export
export const allDemoTeamMembers = allAuthenticTeamMembers;

export const demoFeatures = [
  {
    _id: 'feature-001',
    _type: 'feature',
    title: 'Pro GAMING PROFILE',
    subtitle: 'Create Your Legacy with us',
    description: 'Build your ultimate professional gamer profile with GAMERS TAG, creating a powerful gaming identity to get noticed in the esports and gaming world.',
    shortDescription: 'Professional gamer identity platform',
    icon: 'User',
    image: {
      _type: 'image',
      asset: {
        _ref: 'image-feature-profile',
        _type: 'reference'
      }
    },
    category: 'gaming-profile',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 1
  },
  {
    _id: 'feature-002',
    _type: 'feature',
    title: 'GT CONNECT',
    subtitle: 'Link Everything, Be Everywhere',
    description: 'Connect all your gaming accounts, social media, and digital presence in one unified profile. Make it easy for fans, teams, and sponsors to discover you.',
    shortDescription: 'Unified gaming identity hub',
    icon: 'Link2',
    category: 'social',
    isComingSoon: false,
    isPremium: false,
    sortOrder: 2
  },
  {
    _id: 'feature-003',
    _type: 'feature',
    title: 'GT JOBS',
    subtitle: 'Gaming Career Opportunities',
    description: 'Discover gaming and esports job opportunities, from tournament participation to content creation and team management roles.',
    shortDescription: 'Gaming career platform',
    icon: 'Briefcase',
    category: 'jobs',
    isComingSoon: true,
    isPremium: false,
    sortOrder: 3
  }
];

export const demoTestimonials = [
  {
    _id: 'testimonial-001',
    _type: 'testimonial',
    content: 'GAMERS TAG has revolutionized how I manage my gaming career. The unified platform makes it easy to track my progress across all games and connect with opportunities.',
    author: 'Alex Chen',
    authorPosition: 'Professional Gamer',
    authorCompany: 'Team Nexus',
    authorImage: {
      _type: 'image',
      asset: {
        _ref: 'image-testimonial-alex',
        _type: 'reference'
      }
    },
    rating: 5,
    category: 'gaming',
    isVerified: true,
    isFeatured: true,
    submittedAt: '2024-01-15T10:00:00Z'
  },
  {
    _id: 'testimonial-002',
    _type: 'testimonial',
    content: 'The GT Connect feature is incredible. I can now link all my gaming accounts and social media in one place, making it easier for fans to follow my journey.',
    author: 'Sarah Johnson',
    authorPosition: 'Content Creator',
    authorCompany: 'Gaming Streamer',
    rating: 5,
    category: 'platform',
    isVerified: true,
    isFeatured: true,
    submittedAt: '2024-01-10T14:30:00Z'
  },
  {
    _id: 'testimonial-003',
    _type: 'testimonial',
    content: 'Building highly engineered products with multiple patentable algorithms, latest tech, and complex AI-SaaS interactions that make gamers unique and create sensational products in gaming.',
    author: 'Adesh',
    authorPosition: 'Director of Engineering & Founding Member',
    authorCompany: 'GAMERS TAG',
    rating: 5,
    category: 'platform',
    isVerified: true,
    isFeatured: true,
    submittedAt: '2024-01-20T09:00:00Z'
  },
  {
    _id: 'testimonial-004',
    _type: 'testimonial',
    content: 'The gaming industry stands at the precipice of unprecedented transformation. With GAMERS TAG\'s vision, we\'re not just building a platform – we\'re architecting the future where every gamer becomes a recognized professional, every achievement gets its due recognition, and the entire gaming ecosystem evolves into something extraordinary.',
    author: 'Hemanth',
    authorPosition: 'Chief Security Officer & Founding Member',
    authorCompany: 'GAMERS TAG',
    rating: 5,
    category: 'platform',
    isVerified: true,
    isFeatured: true,
    submittedAt: '2024-01-20T09:15:00Z'
  }
];

export const demoIncubators = [
  {
    _id: 'incubator-001',
    _type: 'incubator',
    name: 'NASSCOM 10,000 Start-ups',
    description: 'GAMERS TAG was selected as one of the programme\'s members, gaining access to NASSCOM\'s mentorship network, investor showcases, and industry events.',
    website: 'https://10000startups.nasscom.in/',
    logo: {
      _type: 'image',
      asset: {
        _ref: 'image-nasscom-logo',
        _type: 'reference'
      }
    },
    partnership: {
      status: 'active',
      benefits: ['Mentorship Network', 'Investor Showcases', 'Industry Events', 'Growth Acceleration']
    },
    category: 'tech-accelerator',
    sortOrder: 1
  },
  {
    _id: 'incubator-002',
    _type: 'incubator',
    name: 'Microsoft for Startups – Founder Hub',
    description: 'As a Founder Hub incubatee, GAMERS TAG receives up to $150k in Azure credits, technical support, and co-selling opportunities.',
    website: 'https://startups.microsoft.com/',
    partnership: {
      status: 'active',
      benefits: ['$150k Azure Credits', 'Technical Support', 'Co-selling Opportunities', 'Sales Team Access']
    },
    category: 'corporate',
    sortOrder: 2
  }
];

export const demoMentors = [
  {
    _id: 'mentor-001',
    _type: 'mentor',
    name: 'Dr. Rajesh Kumar',
    title: 'Gaming Industry Expert',
    company: 'GameDev Consulting',
    bio: 'Former gaming executive with 15+ years in the industry, specializing in product strategy and market expansion.',
    profileImage: {
      _type: 'image',
      asset: {
        _ref: 'image-mentor-rajesh',
        _type: 'reference'
      }
    },
    expertise: ['Product Strategy', 'Market Analysis', 'Team Building'],
    experience: 15,
    mentorshipAreas: ['gaming', 'business', 'product'],
    availability: 'available',
    isActive: true,
    sortOrder: 1
  },
  {
    _id: 'mentor-002',
    _type: 'mentor',
    name: 'Maria Rodriguez',
    title: 'Esports Marketing Director',
    company: 'Digital Sports Media',
    bio: 'Leading esports marketing campaigns and building gaming communities worldwide.',
    expertise: ['Digital Marketing', 'Community Building', 'Brand Strategy'],
    experience: 10,
    mentorshipAreas: ['marketing', 'leadership'],
    availability: 'limited',
    isActive: true,
    sortOrder: 2
  }
];

export const demoSiteSettings = {
  _id: 'settings-001',
  _type: 'settings',
  title: 'GAMERS TAG - The Ultimate Gaming Platform',
  description: 'World\'s first all-in-one gaming super app connecting gamers, creators, and the gaming industry.',
  socialMedia: {
    twitter: 'https://twitter.com/gamerstag',
    linkedin: 'https://linkedin.com/company/gamers-tag',
    discord: 'https://discord.gg/gamerstag',
    youtube: 'https://youtube.com/@gamerstag',
    instagram: 'https://instagram.com/gamerstag'
  },
  contact: {
    email: 'hello@gamerstag.com',
    phone: '+91-XXX-XXX-XXXX',
    address: 'Ahmedabad, Gujarat, India'
  },
  seo: {
    metaTitle: 'GAMERS TAG - World\'s First Gaming Super App',
    metaDescription: 'Join the ultimate gaming community with GAMERS TAG. Create your pro gaming profile, connect with players worldwide, and discover gaming opportunities.',
    keywords: ['gaming platform', 'esports', 'gaming community', 'professional gaming', 'game development']
  }
};