// Updated comprehensive team data for GAMERS TAG
// Organized by departments with authentic member information

export const comprehensiveTeamData = [
  // Core Leadership Team (existing founders and heads)
  {
    _id: 'team-001',
    _type: 'teamMember',
    name: 'Joshua J Kanatt',
    position: 'Founder & Chief Executive Officer',
    department: 'leadership',
    bio: 'Visionary Founder & CEO building game-changing technology at GAMERS TAG. Leading one of the world\'s most innovative gaming super platforms.',
    shortBio: 'Building the future of gaming with innovative technology and visionary leadership',
    profileImage: { _type: 'image', asset: { _ref: 'image-profile-joshua', _type: 'reference' } },
    linkedinUrl: 'https://www.linkedin.com/in/joshuakanatt/',
    expertise: ['Product Management & Strategy', 'Full-Stack Product Ownership', 'SaaS, AI, Fintech, Gaming, EdTech', 'UI/UX Design'],
    isActive: true,
    isFounder: true,
    sortOrder: 1
  },
  {
    _id: 'team-002',
    _type: 'teamMember',
    name: 'Harsh Singh',
    position: 'Lead Frontend Developer',
    department: 'engineering',
    bio: 'Leading frontend development with expertise in modern web technologies and user interface design.',
    shortBio: 'Expert frontend developer creating exceptional user experiences',
    linkedinUrl: 'https://www.linkedin.com/in/harsh-singh',
    expertise: ['React', 'TypeScript', 'Frontend Architecture', 'UI/UX Implementation'],
    isActive: true,
    isFounder: false,
    sortOrder: 2
  },
  {
    _id: 'team-003',
    _type: 'teamMember',
    name: 'Paul Dickinson',
    position: 'Head of Operations',
    department: 'operations',
    bio: 'Strategic operations leader ensuring seamless business processes and organizational efficiency.',
    shortBio: 'Operations expert driving organizational excellence and strategic growth',
    linkedinUrl: 'https://www.linkedin.com/in/paul-dickinson',
    expertise: ['Operations Management', 'Strategic Planning', 'Process Optimization', 'Business Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 3
  },

  // Finance & Administration Team
  {
    _id: 'finance-001',
    _type: 'teamMember',
    name: 'Tintu Tomy',
    position: 'Senior Financial Analyst',
    department: 'business',
    bio: 'Senior financial analyst managing financial planning, analysis, and strategic financial decision-making.',
    shortBio: 'Expert in financial analysis and strategic planning',
    linkedinUrl: 'https://www.linkedin.com/in/tintu-tomy-93655a24',
    expertise: ['Financial Analysis', 'Strategic Planning', 'Budget Management', 'Financial Reporting'],
    isActive: true,
    isFounder: false,
    sortOrder: 10
  },
  {
    _id: 'finance-002',
    _type: 'teamMember',
    name: 'Dibin Jose Vadakkan',
    position: 'Financial Analyst',
    department: 'business',
    bio: 'Financial analyst supporting comprehensive financial operations and analysis.',
    shortBio: 'Dedicated financial professional driving data-driven decisions',
    linkedinUrl: 'https://www.linkedin.com/in/dibin-jose-vadakkan-69109179',
    expertise: ['Financial Analysis', 'Data Analysis', 'Financial Modeling', 'Reporting'],
    isActive: true,
    isFounder: false,
    sortOrder: 11
  },
  {
    _id: 'finance-003',
    _type: 'teamMember',
    name: 'Mariya Joshy',
    position: 'Financial Analyst',
    department: 'business',
    bio: 'Financial analyst contributing to comprehensive financial planning and analysis.',
    shortBio: 'Financial expert supporting strategic business decisions',
    linkedinUrl: 'https://www.linkedin.com/in/mariya-joshy-97bba4222',
    expertise: ['Financial Planning', 'Analysis', 'Budget Control', 'Financial Reporting'],
    isActive: true,
    isFounder: false,
    sortOrder: 12
  },
  {
    _id: 'finance-004',
    _type: 'teamMember',
    name: 'Abhishek S Nair',
    position: 'Financial Analyst',
    department: 'business',
    bio: 'Financial analyst managing financial operations and strategic analysis.',
    shortBio: 'Results-driven financial analyst with strategic focus',
    linkedinUrl: 'https://www.linkedin.com/in/abhishek-s-nair50',
    expertise: ['Financial Operations', 'Strategic Analysis', 'Risk Assessment', 'Financial Control'],
    isActive: true,
    isFounder: false,
    sortOrder: 13
  },
  {
    _id: 'finance-005',
    _type: 'teamMember',
    name: 'Abel Antony',
    position: 'Financial Analyst',
    department: 'business',
    bio: 'Financial analyst supporting business operations with comprehensive financial insights.',
    shortBio: 'Financial professional driving business growth through analysis',
    linkedinUrl: 'https://www.linkedin.com/in/abel-antony-benny',
    expertise: ['Business Analysis', 'Financial Planning', 'Cost Management', 'Performance Analysis'],
    isActive: true,
    isFounder: false,
    sortOrder: 14
  },
  {
    _id: 'finance-006',
    _type: 'teamMember',
    name: 'Jen Joy',
    position: 'Financial Analyst',
    department: 'business',
    bio: 'Financial analyst contributing to strategic financial planning and operations.',
    shortBio: 'Analytical professional supporting financial excellence',
    linkedinUrl: 'https://www.linkedin.com/in/jentjoy',
    expertise: ['Financial Analysis', 'Strategic Planning', 'Data Management', 'Financial Controls'],
    isActive: true,
    isFounder: false,
    sortOrder: 15
  },
  {
    _id: 'finance-007',
    _type: 'teamMember',
    name: 'Nasrin K',
    position: 'Financial Analyst',
    department: 'business',
    bio: 'Financial analyst managing comprehensive financial operations and analysis.',
    shortBio: 'Detail-oriented financial professional ensuring accuracy',
    linkedinUrl: 'https://www.linkedin.com/in/nasrin-k',
    expertise: ['Financial Operations', 'Accuracy Management', 'Financial Reporting', 'Compliance'],
    isActive: true,
    isFounder: false,
    sortOrder: 16
  },
  {
    _id: 'finance-008',
    _type: 'teamMember',
    name: 'Jerin Mathew',
    position: 'Financial Analyst',
    department: 'business',
    bio: 'Financial analyst supporting business growth through strategic financial management.',
    shortBio: 'Strategic financial analyst driving business success',
    linkedinUrl: 'https://www.linkedin.com/in/jerin-mathew-60214a1b9',
    expertise: ['Strategic Finance', 'Business Growth', 'Financial Strategy', 'Performance Metrics'],
    isActive: true,
    isFounder: false,
    sortOrder: 17
  },

  // Human Resources Team
  {
    _id: 'hr-001',
    _type: 'teamMember',
    name: 'Fathima Nihma',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager leading talent acquisition, employee development, and organizational culture.',
    shortBio: 'HR leader fostering exceptional workplace culture',
    linkedinUrl: 'https://www.linkedin.com/in/fathima-nihma',
    expertise: ['Talent Acquisition', 'Employee Development', 'Organizational Culture', 'HR Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 20
  },
  {
    _id: 'hr-002',
    _type: 'teamMember',
    name: 'Himani Sharma',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager specializing in employee relations and human resource development.',
    shortBio: 'HR professional dedicated to employee success',
    linkedinUrl: 'https://www.linkedin.com/in/himanisharma062',
    expertise: ['Employee Relations', 'HR Development', 'Performance Management', 'Team Building'],
    isActive: true,
    isFounder: false,
    sortOrder: 21
  },
  {
    _id: 'hr-003',
    _type: 'teamMember',
    name: 'Suhitha Suresh',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager focused on talent management and organizational effectiveness.',
    shortBio: 'Talent management expert driving organizational growth',
    linkedinUrl: 'https://www.linkedin.com/in/suhitha1722',
    expertise: ['Talent Management', 'Organizational Effectiveness', 'HR Operations', 'Strategic HR'],
    isActive: true,
    isFounder: false,
    sortOrder: 22
  },
  {
    _id: 'hr-004',
    _type: 'teamMember',
    name: 'Rishitha Jain',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager contributing to comprehensive human resource management and development.',
    shortBio: 'HR specialist focused on comprehensive people management',
    linkedinUrl: 'https://www.linkedin.com/in/rishita-jain-24890b30a',
    expertise: ['People Management', 'HR Policies', 'Employee Engagement', 'Workplace Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 23
  },
  {
    _id: 'hr-005',
    _type: 'teamMember',
    name: 'Sukhmani Kaur',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager managing talent acquisition and employee development programs.',
    shortBio: 'Dynamic HR professional driving talent excellence',
    linkedinUrl: 'https://www.linkedin.com/in/itssukhmanikaur',
    expertise: ['Talent Acquisition', 'Employee Development', 'HR Programs', 'Team Leadership'],
    isActive: true,
    isFounder: false,
    sortOrder: 24
  },
  {
    _id: 'hr-006',
    _type: 'teamMember',
    name: 'Iti Jain',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager supporting comprehensive human resource operations and strategy.',
    shortBio: 'HR professional committed to organizational excellence',
    expertise: ['HR Operations', 'Strategic Planning', 'Employee Support', 'Process Improvement'],
    isActive: true,
    isFounder: false,
    sortOrder: 25
  },
  {
    _id: 'hr-007',
    _type: 'teamMember',
    name: 'Kartheek Chilukoti',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager focused on employee relations and organizational development.',
    shortBio: 'HR leader enhancing employee experience and growth',
    linkedinUrl: 'https://www.linkedin.com/in/kartheek-chilukoti-038185228',
    expertise: ['Employee Relations', 'Organizational Development', 'HR Strategy', 'Performance Management'],
    isActive: true,
    isFounder: false,
    sortOrder: 26
  },
  {
    _id: 'hr-008',
    _type: 'teamMember',
    name: 'Poojitha Pasham',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager specializing in talent management and workplace culture development.',
    shortBio: 'HR expert building exceptional workplace culture',
    linkedinUrl: 'https://www.linkedin.com/in/poojitha-pasham-2355652a1',
    expertise: ['Talent Management', 'Workplace Culture', 'HR Development', 'Employee Engagement'],
    isActive: true,
    isFounder: false,
    sortOrder: 27
  },
  {
    _id: 'hr-009',
    _type: 'teamMember',
    name: 'Butool Zehra Jafri',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager contributing to strategic human resource management and development.',
    shortBio: 'Strategic HR professional driving organizational success',
    linkedinUrl: 'https://www.linkedin.com/in/butoolzehra30',
    expertise: ['Strategic HR', 'Organizational Management', 'Employee Development', 'HR Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 28
  },
  {
    _id: 'hr-010',
    _type: 'teamMember',
    name: 'Mannat Malhotra',
    position: 'HR Manager',
    department: 'hr',
    bio: 'HR Manager managing comprehensive human resource operations and employee relations.',
    shortBio: 'HR professional dedicated to employee success and growth',
    linkedinUrl: 'https://www.linkedin.com/in/mannat-malhotra-82900a216',
    expertise: ['HR Operations', 'Employee Relations', 'Talent Development', 'Organizational Growth'],
    isActive: true,
    isFounder: false,
    sortOrder: 29
  },

  // Design Team
  {
    _id: 'design-001',
    _type: 'teamMember',
    name: 'Nithin George',
    position: 'Senior Product Designer',
    department: 'design',
    bio: 'Senior Product Designer leading design strategy and creating exceptional user experiences.',
    shortBio: 'Design leader crafting innovative user experiences',
    linkedinUrl: 'https://www.linkedin.com/in/nithin-george-308a9458/',
    expertise: ['Product Design', 'Design Strategy', 'User Experience', 'Design Leadership'],
    isActive: true,
    isFounder: false,
    sortOrder: 30
  },
  {
    _id: 'design-002',
    _type: 'teamMember',
    name: 'Haniya Abdul Rahman',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design team member contributing to innovative design solutions and user interface development.',
    shortBio: 'Creative designer focused on innovative solutions',
    linkedinUrl: 'https://www.linkedin.com/in/haniya-ar',
    expertise: ['UI Design', 'Creative Solutions', 'Design Innovation', 'Visual Communication'],
    isActive: true,
    isFounder: false,
    sortOrder: 31
  },
  {
    _id: 'design-003',
    _type: 'teamMember',
    name: 'Nithin Dhawane',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design team member specializing in user interface and visual design excellence.',
    shortBio: 'UI specialist creating exceptional visual experiences',
    linkedinUrl: 'https://www.linkedin.com/in/nitin-dhawane-39b07515a',
    expertise: ['UI Design', 'Visual Design', 'Design Excellence', 'User Interface'],
    isActive: true,
    isFounder: false,
    sortOrder: 32
  },
  {
    _id: 'design-004',
    _type: 'teamMember',
    name: 'Kevin George',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design team member focused on creating engaging and user-friendly design solutions.',
    shortBio: 'Design professional creating engaging user solutions',
    linkedinUrl: 'https://www.linkedin.com/in/kevin-george-58b5701a1',
    expertise: ['User-Friendly Design', 'Engagement Design', 'Design Solutions', 'Creative Development'],
    isActive: true,
    isFounder: false,
    sortOrder: 33
  },
  {
    _id: 'design-005',
    _type: 'teamMember',
    name: 'Alen Joshy',
    position: 'Design Team Member',
    department: 'design',
    bio: 'Design team member contributing to comprehensive design development and innovation.',
    shortBio: 'Innovative designer driving design excellence',
    linkedinUrl: 'https://www.linkedin.com/in/alen-joshy-4025a41bb',
    expertise: ['Design Development', 'Design Innovation', 'Creative Excellence', 'Design Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 34
  },

  // Technology Team
  {
    _id: 'tech-001',
    _type: 'teamMember',
    name: 'Mohd Amber Rizvi',
    position: 'Core Tech Member',
    department: 'engineering',
    bio: 'Core technology team member leading technical innovation and development excellence.',
    shortBio: 'Technical leader driving innovation and development',
    linkedinUrl: 'https://www.linkedin.com/in/mohd-amber-rizvi-93a55a201',
    expertise: ['Technical Leadership', 'Innovation', 'Development Excellence', 'Technology Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 40
  },
  {
    _id: 'tech-002',
    _type: 'teamMember',
    name: 'Shivansh Verma',
    position: 'Core Tech Member',
    department: 'engineering',
    bio: 'Core technology team member specializing in advanced development and technical solutions.',
    shortBio: 'Tech expert creating advanced solutions',
    linkedinUrl: 'https://www.linkedin.com/in/meet-shivanshverma',
    expertise: ['Advanced Development', 'Technical Solutions', 'Software Engineering', 'Innovation'],
    isActive: true,
    isFounder: false,
    sortOrder: 41
  },
  {
    _id: 'tech-003',
    _type: 'teamMember',
    name: 'Jayandra Todawat',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer contributing to cutting-edge software development and technical excellence.',
    shortBio: 'Software developer focused on technical excellence',
    linkedinUrl: 'https://www.linkedin.com/in/jayndra-todawat',
    expertise: ['Software Development', 'Technical Excellence', 'Programming', 'Code Quality'],
    isActive: true,
    isFounder: false,
    sortOrder: 42
  },
  {
    _id: 'tech-004',
    _type: 'teamMember',
    name: 'Sakshi Dhoni',
    position: 'Developer',
    department: 'engineering',
    bio: 'Developer specializing in innovative software solutions and development practices.',
    shortBio: 'Innovative developer creating robust solutions',
    linkedinUrl: 'https://www.linkedin.com/in/sakshidhoni',
    expertise: ['Software Solutions', 'Development Practices', 'Innovation', 'Technical Implementation'],
    isActive: true,
    isFounder: false,
    sortOrder: 43
  },

  // Marketing & Content Team
  {
    _id: 'marketing-001',
    _type: 'teamMember',
    name: 'Ditto Johnson',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager driving digital engagement and brand presence across platforms.',
    shortBio: 'Digital marketing expert building brand engagement',
    linkedinUrl: 'https://www.linkedin.com/in/ditto-johnson-941267249',
    expertise: ['Social Media Strategy', 'Digital Engagement', 'Brand Management', 'Content Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 50
  },
  {
    _id: 'marketing-002',
    _type: 'teamMember',
    name: 'Aiswarya Madhu',
    position: 'Social Media Manager',
    department: 'marketing',
    bio: 'Social Media Manager creating compelling content and managing brand communications.',
    shortBio: 'Content strategist enhancing brand communications',
    linkedinUrl: 'https://www.linkedin.com/in/vallathaiswarya',
    expertise: ['Content Creation', 'Brand Communications', 'Social Strategy', 'Digital Marketing'],
    isActive: true,
    isFounder: false,
    sortOrder: 51
  },
  {
    _id: 'marketing-003',
    _type: 'teamMember',
    name: 'Shamil Mohamed',
    position: 'Brand Manager',
    department: 'marketing',
    bio: 'Brand Manager leading brand strategy and market positioning initiatives.',
    shortBio: 'Brand strategist driving market positioning',
    linkedinUrl: 'https://www.linkedin.com/in/muhammed-shamil-thottungal',
    expertise: ['Brand Strategy', 'Market Positioning', 'Brand Development', 'Strategic Marketing'],
    isActive: true,
    isFounder: false,
    sortOrder: 52
  },

  // Quality Assurance Team
  {
    _id: 'qa-001',
    _type: 'teamMember',
    name: 'Jilha Jose',
    position: 'App Tester',
    department: 'engineering',
    bio: 'App Tester ensuring quality assurance and comprehensive testing of applications.',
    shortBio: 'QA expert ensuring application excellence',
    linkedinUrl: 'https://www.linkedin.com/in/jilha-jos/',
    expertise: ['Quality Assurance', 'App Testing', 'Test Strategy', 'Quality Control'],
    isActive: true,
    isFounder: false,
    sortOrder: 60
  },
  {
    _id: 'qa-002',
    _type: 'teamMember',
    name: 'Ardra Shashidharan',
    position: 'App Tester',
    department: 'engineering',
    bio: 'App Tester specializing in comprehensive testing and quality assurance processes.',
    shortBio: 'Testing specialist focused on quality excellence',
    linkedinUrl: 'https://www.linkedin.com/in/ardra-sasidharan-05a861211',
    expertise: ['Comprehensive Testing', 'QA Processes', 'Test Automation', 'Quality Excellence'],
    isActive: true,
    isFounder: false,
    sortOrder: 61
  },

  // Esports Team
  {
    _id: 'esports-001',
    _type: 'teamMember',
    name: 'Jeethu Singh',
    position: 'Esports Manager',
    department: 'marketing',
    bio: 'Esports Manager leading competitive gaming initiatives and community engagement.',
    shortBio: 'Esports leader driving competitive gaming excellence',
    linkedinUrl: 'https://www.linkedin.com/in/jeetu-singh-574665292',
    expertise: ['Esports Management', 'Competitive Gaming', 'Community Engagement', 'Gaming Strategy'],
    isActive: true,
    isFounder: false,
    sortOrder: 70
  },
  {
    _id: 'esports-002',
    _type: 'teamMember',
    name: 'Indrajith Ajith',
    position: 'Esports Manager',
    department: 'marketing',
    bio: 'Esports Manager contributing to competitive gaming programs and strategic development.',
    shortBio: 'Esports strategist enhancing competitive programs',
    expertise: ['Competitive Gaming', 'Strategic Development', 'Esports Programs', 'Gaming Excellence'],
    isActive: true,
    isFounder: false,
    sortOrder: 71
  }
];

// Export for compatibility
export const allDemoTeamMembers = comprehensiveTeamData;